### ISSUE TITLE
Auditions Creation - Scheduled vs Non-Scheduled

### ISSUE THREAD

**Issue by stumo** [camdram/camdram#103]
I am not sure that the current auditions creation is quite what we want

As best I can make out, the current V2 logic is:
- Any entries in the "Sessions" list result in an audition with NonScheduled = false, which has date, start time, end time and location all set.
- If there is an entry in the "Contact Details" list, then we create an audition with NonScheduled = true, using the Advert Expiry Date & Expiry Time as the audition date & start time. Contact Details goes into the Location field. 

There is also a Display field in the database, and I haven't yet worked out what that is for. As far as I can tell, everything in old camdram (content/69.php) seems to only select auditions with display = 0 but I cannot find where it is set. None of the rows in camdram v1 have display = 1 anyway! 

I think the way to go is edit the form so that you can either fill in several sessions, or have a single non-scheduled session for contact details. There are a few shows in the camdram v1 database that have both, but not many and none with future auditions.

We also have the question of what we should do with auditions in the past - at the moment they aren't visible if you're editing the form; I would suggest they should be, but with formatting identifying them as past - so that if you have accidentally set a value in the past you can move it to the future.

**Comment by sigilion** [comment]
For some reason the audition ad for trade is still showing up on the show page, which I don't think it should be (it doen't seem to show up on the auditions page). I think it may be related to this in some way, although without database access I have no idea what it's doing.

**Comment by philosophicles** [comment]
@sigilion Did you get my 'welcome' email on the 10th?
