### ISSUE TITLE
Extend functionality of User Admin screen

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#116]
The user admin screen http://beta.camdram.net/admin/users is missing a few useful features.  (We can fallback to V1 for these for now; writing down for the longer-term.)
- Issue a password reset
- See the UserID in the table-list of users (handy for more complex support issues)
- Sort the list

The roles also don't appear to be displaying entirely correctly/consistently for each user.  E.g. http://beta.camdram.net/admin/users/1 does not have ROLE_SUPER_ADMIN while /445 (me) does; we both have the necessary magic flag within v1.  I'm not sure if this is an issue, undeveloped feature, or something else.

**Comment by philosophicles** [comment]
It would also be helpful if the user search matched against email address, e.g. entering a CRSid would find the person.

**Comment by philosophicles** [comment]
Related to user search behaviour - the autocomplete drop-down seems to apply a DISTINCT filter.  E.g. if there are two users with the same name, only one entry in the drop-down list is shown (which consistently takes me to the record with lower/older user id I think).  Both entries should be shown.

**Comment by philosophicles** [comment]
@hoyes I've just re-remembered this and would say that the user search features commented above do need to be part of Laurie. (This issue is in Laurie so AOK, but your recent webteam email didn't list this one - hence just giving it a nudge.)

**Comment by hoyes** [comment]
Understood and noted!

**Comment by philosophicles** [comment]
Another element of this functionality is the ability to edit users' roles/privileges, e.g. give a user ROLE_SUPER_ADMIN or revoke it. 

This currently still has to be done via V1 so, whilst really rare, is ideally necessary before decommissioning V1. (Worst case we could do it in SQL directly, it is that rare...)

**Comment by CHTJonas** [comment]
Just giving this a bump as it may be relevant given your recent work with Elasticsearch @hoyes

**Comment by CHTJonas** [comment]
The ability to give/revoke ROLE_SUPER_ADMIN privileges to a user I think is the broad intention of #399. There seems to be a suggestion floating somewhere that this shouldn't be done via the Camdram UI, but via a console command such as eg. #394.

From the original issue we have:

- [x] Password reset
- [x] User IDs
- [ ] ~~Edit privileges~~
- [ ] Table sorting
- [ ] Fix searching
