### ISSUE TITLE
Administration menu doesn't have Show Admin

### ISSUE THREAD

**Issue by edlouth** [camdram/camdram#128]
As a camdram administrator I have to use the dropdown menu on the home diary bar.  I naturally looked to the administration menu at the top of the page.
In my mind clicking on administration would take you directly to show admin or similar.

**Comment by CHTJonas** [comment]
Resurrecting this old issue once more: I agree with @ajf58 and suggest we close this issue as it only affects fewer than say 10 people. Maybe we could further clarify be renaming the "Administration" link to "Site Administration"?
