### ISSUE TITLE
Name search not sorted by date descending

### ISSUE THREAD

**Issue by dstansby** [camdram/camdram#129]
Camdram v1 sorts name searching by date of latest show descending - ie. more recently active people at the top. Currently Camdram v2 doesn't do this, and so it takes a lot of down button presses to get to more recently active people.

**Comment by dtwood** [comment]
This seems to have come back - see "Miss Fluffycat and Her Kittens", in Dec 2093 / Nov 1957

**Comment by dtwood** [comment]
Ah, so the search order is currently correct, it just shows the wrong date in the autocomplete

**Comment by CHTJonas** [comment]
This appears to have been corrected in a commit(s) since 2015. The "Miss Fluffycat and Her Kittens" search now shows Nov 1957 which I presume is the correct behaviour. Likewise with "Hotel Paradsio".

**Comment by CHTJonas** [comment]
From recent conversation on Gitter post the upgrade to Elasticsearch:
> the ranking is currently: all societies, all venues, shows ordered by start date + people ordered by last active date
