### ISSUE TITLE
Improve styling of unordered list elements

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#133]
E.g. the 'About' page.  Pretty minor I know but (until I hear objections) I'd like to adjust the CSS for a larger font size and nicer indentation on HTML ul elements.  I intend to play with this sometime as a Camdram learning exercise.

**Comment by CHTJonas** [comment]
@philosophicles I've removed you & self-assigned this as I've been playing around with my in-browser element inspector and think I've come up with a neat solution for this problem, under the guise that nothing further has been done on this since 201. Hope that's alright! 👌
