### ISSUE TITLE
Some diary bugs/improvements (layout not content)

### ISSUE THREAD

**Issue by jamesterjlrb** [camdram/camdram#165]
So a few partly related issues/potential improvements I've spotted.

On the diary page, the autoloading means that it's impossible without doing weird things to get to the footer. It also seems to load weeks forever, regardless of whether there exist any shows in these dates. Could we make the footer always sit at the bottom of the screen on this page? A return to top button might also be quite useful.

Also, on a society's page, the diary shortens by removing empty weeks. e.g. (https://beta.camdram.net/societies/cambridge-university-amateur-dramatic-club) While this is great, it'd be good to have some indication of when weeks have been removed (e.g. a horizontal line between non consecutive weeks where weeks have been removed.) It'd also be good to extend the removal of empty weeks (with indication) to the diary page. This'd solve the loading of empty weeks forever into the future issue.

On the homepage, the week by week viewer at the top will also display empty weeks. While I don't think we should remove said weeks from the navigator, it'd be good to have an indication that they're empty, or maybe make them non selectable (would probably also want an indication, although this could be more subtle. Maybe make the period name (e.g. summer vacation) black instead of orange)? Alternatively could we each week in the navigator have a count of how many shows there are that week?

**Comment by ajf58** [comment]
Closing as won't fix.
