### ISSUE TITLE
Ensure v1 RSS feed and iCal URLs redirect correctly

### ISSUE THREAD

**Issue by hoyes** [camdram/camdram#178]
I'm not sure how widely used they are, but the following feeds (plus maybe others I haven't found) should probably redirect to their v2 counterparts working after we switch to v2. (I think v2 does support all these, if not perhaps just redirect to v1 for now)

http://www.camdram.net/rss.php?type=shows
http://www.camdram.net/rss.php?type=techies
http://www.camdram.net/ical
http://www.camdram.net/ical/society-name 
http://www.camdram.net/ical/venue-name

**Comment by philosophicles** [comment]
There was one other V1 feed not listed above: http://www.camdram.net/rss.php?type=events
