### ISSUE TITLE
Cannot approve shows (V1 or V2)

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#182]
Trying to approve a recently-submitted show that's not affiliated to a known society or venue (short film).

Clicking 'Authorize' in V1 causes page refresh with a visible error message at the top "An error occured in processing your request / Please try again."

Tried again in V2; 'Approve this show' button causes screen to refresh but show is not approved.  

Therefore this bug is two things really:
(1) Underlying problem preventing show(s) being authorised, at least by me 
(2) V2 interface not presenting suitable feedback to user that this action has failed

**Comment by ajf58** [comment]
Is this still an open issue?

**Comment by philosophicles** [comment]
I believe this is here solely as a reminder to write an automation test covering it... @hoyes ?

**Comment by hoyes** [comment]
Yes that was the idea...still probably a good idea to have a test around this so will keep open...
