### ISSUE TITLE
Acessing show admin requires two logins

### ISSUE THREAD

**Issue by dstansby** [camdram/camdram#184]
I've just tried to access the show admin page, after logging in via. Raven. When I pressed the "Show Admin" link from the drop down, Camdram required me to log in again with my Camdram password.

I'm not sure whether this is intended behavior, but it seems like the second login is superfluous to me.

**Comment by hoyes** [comment]
This is more complex than I originally thought, and will be easier without having to maintain v1 support... bumping to next milestone.

**Comment by hoyes** [comment]
This was recently implemented in the extlogin branch (now merged into master)
