### ISSUE TITLE
Allow shows to be associated with more than one society

### ISSUE THREAD

**Issue by hoyes** [camdram/camdram#191]
At the moment, each show can have 0 or 1 societies attached. It would be nice if more than one could be associated (e.g. when a show is co-funded).

Parts:
- DB changes - there'll have to be an extra link table as shows <> societies will become a many-to-many mapping
- Make show pages display the multiple societies in a list
- UI changes to the add/edit show form

In the past this has been solved by storing the 2 society names as raw text and omitting the links to the individual societies. Even though this is still a fairly rare scenario (maybe once a term), it's arguably more a problem now that we have proper society pages and an API, as it would be annoying if the show wasn't included in both societies' feeds.

**Comment by philosophicles** [comment]
@GKFX I've added this to the DB structural changes project, this is a super-long-standing request/desire and one that actually comes up on a fairly regular basis in production usage of the site.
