### ISSUE TITLE
Admin tools for 'people' management

### ISSUE THREAD

**Issue by hoyes** [camdram/camdram#195]
We need to replicate the v1 tools for people management.
- A list of all people with a search tool
- Search for 'orphaned' people
- The ability to merge 2 people together (covered by #149)

There are almost certainly things I've forgotten...please add them as comments!

**Comment by hoyes** [comment]
I have:
 * Added an admin-only 'merge' link to the toolbar on the existing people pages, in the spirit of only having one URL per resource.
 * Fixed the existing 'camdram:people:remove-orphaned' console command.

I think this achieves the aim of this ticket... people names etc are already editable from the people page. Is there anything missing?

**Comment by hoyes** [comment]
Oh and the idea of the console command rather than UI for removing orphaned people is that it can be added to a cron so it happens automatically. I'm thinking of delaying setting this up though until we're able to add a timestamp field to each row though so we can retain those created in the last 24 hours or something.

**Comment by philosophicles** [comment]
Yes, I agree this ticket's been achieved. Are you wanting to keep it open until the cron job is set up?

**Comment by hoyes** [comment]
Yes I'll keep open. Will move to next milestone

**Comment by GKFX** [comment]
Is this done? I removed a person's only show a couple of days back (https://www.camdram.net/people/failed-flooder-of-the-adc-village; someone managed to enter the person and their role the wrong way round) and they've been removed from the database, which looks like it was the only outstanding thing.

**Comment by hoyes** [comment]
Yea let's close. Can open new ticket(s) if another new is discovered.

**Comment by CHTJonas** [comment]
It would be great if deleting an orphaned person (and presumably venue, society or show too) also removed them from the search index but I'm not sure how easy that would be...

**Comment by hoyes** [comment]
That should now be the case with Elasticsearch, so long as it's removed via Camdram code so that the sync hook is triggered. The Sphinx hook was a bit broken.

**Comment by GKFX** [comment]
Does the search index get rebuilt occasionally to fix that sort of thing?

**Comment by hoyes** [comment]
I thought there was something running daily, but I can't find the crontab entry on Tiberius.... 

Will add a nightly rebuild as part of #398

**Comment by CHTJonas** [comment]
Rebuilding is a reasonably computationally intensive (~5 minutes of wall time on the prod db I think when I ran it) operation during which we lose search functionality. I'm just wondering how beneficial it actually is to fully purge and rebuild the index daily if we're purging orphans using code hooks? I happy to be quiet if you disagree @hoyes but would a better option not be to try and detect orphans and alert the dev team so that the removal hooks can be fixed (and the index then rebuilt manually)?

**Comment by hoyes** [comment]
Yea that's a much better strategy. I'm probably too used to the hooks being flaky in recent times...

**Comment by GKFX** [comment]
It might still be worthwhile to add an occasional rebuild to fix errors that for whatever reason (admin interventions...) don't trigger a hook. 5 minutes of no search every night might be excessive but e.g. once a fortnight at 4am would seem fine.

**Comment by CHTJonas** [comment]
Yeah I agree that sounds good George. On the specific time, @hoyes do we have any kind of web analytics so we can see how number of web requests varies with date/time/term/season/year?

**Comment by hoyes** [comment]
I added @CHTJonas to our Google analytics a couple of weeks back so should be able to find out there. Let us know if it didn't work. (@GKFX can add you too but need an e-mail address linked to a Google account).

**Comment by hoyes** [comment]
Just looked at it's a toss-up between 4am and 5am for the quietest period.

**Comment by CHTJonas** [comment]
Can you link me to that Pete? I'm struggling to set the timebase on Google's UI 🤨

**Comment by CHTJonas** [comment]
Actually disregard that - found it!
