### ISSUE TITLE
Roles

### ISSUE THREAD

**Issue by hoyes** [camdram/camdram#20]
Create a searchable list of theatrical roles (e..g producer, lighting designer, actor etc).

Annotate existing show data and production team vacancies to link to the 'roles' table (or whatever we decide to call it). Probably still allow esoteric show positions, e.g. "CEO Carts'R'Us", but ensure we know that it's a more specific form of a 'Set Builder'.

Create a page describing each major role, linking to relevant infobase pages and current relevant production team vacancies.

**Comment by GKFX** [comment]
Closing in favour of #159, which has discussed this in some depth.
