### ISSUE TITLE
Ordering of search results

### ISSUE THREAD

**Issue by stumo** [camdram/camdram#202]
I wonder if we might be able to optimise search results for shows by showing the closest (either in the future or past) top.

E.g. at the moment if you search for "Yeomen" and the top result is 2004; the closest result choronologically, in Jan 2015, is 4th entry.

**Comment by philosophicles** [comment]
@hoyes and @stumo does this issue still need to be open? When I search for 'Yeoman' on the live site, the sort order is sensible with most recent at the top/first.

**Comment by StuartMoore** [comment]
Looks like it can be closed.

**Comment by stumo** [comment]
Looks like it can be closed. (Sorry, shouldn't post from the work github account)
