### ISSUE TITLE
Audition advert issues

### ISSUE THREAD

**Issue by alexbrett** [camdram/camdram#214]
If someone enters invalid data (or what is believed to be invalid data) in an audition advert, while the HTTP POST gets a 400, the UI just sends the user back to the editor page, with no explanation that anything is wrong, thus potentially giving the false impression that the advert has been saved.

Identified from support ticket 75063.

**Comment by philosophicles** [comment]
Another validation problem in the same vein is that you can add scheduled auditions in the past, and don't get any feedback that that's wrong. I'm not sure if they're getting written to the DB (and not visible because their in the past) or not getting written to DB with no error.

**Comment by philosophicles** [comment]
Also think this relates to #103 ?
