### ISSUE TITLE
"Search is not available at the moment" when adding society to show page

### ISSUE THREAD

**Issue by tazsc2** [camdram/camdram#2313]
Hello :) I have tried on different browsers, on both my phone and laptop, and via other users accounts, but we have not been able to add "Bread Theatre and Film Society" to the shows we are funding next term: when we go to "add a society", it's just saying "search is not available at the moment", so we're not able to add our registered society to show pages.

This has been an issue for me dating back to October 2023, but in the past it would normally work if you kept reloading the edit show details page, eventually the search would work. Not sure if this is a bug or an issue on my end. Thank you for all your work on this incredibly useful website! :)

**Comment by GKFX** [comment]
We seem to have developed some sort of performance issues where some operations such as saving edits to a show can take a very long time to complete. I am wondering if search could also be taking a very long time to give results in some cases and timing out.

**Comment by tazsc2** [comment]
That might be the case! The “solution” I found was to type in the society name, and then click save again and again until the search function worked.
