### ISSUE TITLE
500 Error on trying to approve admin request

### ISSUE THREAD

**Issue by jamesterjlrb** [camdram/camdram#245]
When someone requests admin rights on a show, it shows up as a yes no decision on that show's admin page, but 500 error occurs when trying to make a decision. Also only one request was shown on  current camdram, but two on old from the same person, may be related to the issue. Marlowe Showcase 2015 for reference.

**Comment by CHTJonas** [comment]
I have tested this by impersonating the 'Test User' account and am unable to reproduce, either by accepting or denying the admin request, so am closing.
