### ISSUE TITLE
Diary usability tweaks

### ISSUE THREAD

**Issue by Will-W** [camdram/camdram#260]
Like all the best stalkers, I've been using the Camdram Diary page to track where ETG have got to (which it does very well)
A couple of small usability suggestions:
* A highlight on the current day. Not immediately obvious where you are in the week, and actually at a glance, the week highlight seems to be a header for a particular (wrong) day.
* A pair of next week/previous week buttons? I just kind of expect them to be there (cf Google Calendar etc.), and then they aren't and I have to use the week browser.

**Comment by hoyes** [comment]
Cheers David - I've merged that in (made a couple of tweaks as detailed in the commit message).

**Comment by Will-W** [comment]
Good stuff!
