### ISSUE TITLE
Make HTML version of authorisation emails

### ISSUE THREAD

**Issue by dstansby** [camdram/camdram#265]
Came up in #241, I'm currently working on this in https://github.com/dstansby/camdram/tree/gmail-oneclick

**Comment by dstansby** [comment]
Currently trying to get my local version to send me an email - I've set both the delivery and sender in parameters to dstansby@gmail.com and it's not working, do I need to fill in my gmail details too?

**Comment by hoyes** [comment]
Hmm the 'sender' is just used to set the 'from' header which doesn't actually have any effect on the delivery of the email. As the configuration is set to 'gmail' by default it will currently be attempting to SMTP gmail with a blank username and password, which obviously fails. For the email actions to work, you should enter your gmail email address in 'mailer_user' and password (app-specific if you use 2-factor) in 'mailer_password'.

Alternatively you can just change 'gmail' to 'mail', which will cause the email to be sent by your local computer, but it may end up in the spam folder as you're not a known mail server, and the email actions won't work.

The below may be useful:
http://symfony.com/doc/current/cookbook/email/email.html#configuration
http://symfony.com/doc/current/reference/configuration/swiftmailer.html#full-default-configuration
http://symfony.com/doc/current/cookbook/email/gmail.html

**Comment by dstansby** [comment]
Yay, I've got sending emails from my local copy working now! Hopefully not too long until I can fix this.

**Comment by hoyes** [comment]
Hmm it looks like you need SPF/DKIM set up on the camdram.net domain record even for testing to work. Pinging @alexbrett to see if he has time to look at this - I've no idea how involved a process this is...

**Comment by alexbrett** [comment]
I can put an SPF record in pretty trivially as it's just a DNS entry, DKIM is a bit more complicated as it involves making the mailservers able to sign e-mails properly. Will SPF on its own be sufficient, or is DKIM a requirement?
