### ISSUE TITLE
Facebook/Twitter icons blocked by Ad Block Plus

### ISSUE THREAD

**Issue by dstansby** [camdram/camdram#277]
There should be little icons just to the left of news item titles, but for some odd reason they're not showing up. The HTML I'm getting on live V2 seems to make sense and the images exist, but they're showing up as size 0 x 18.

Using Firefox 34.0.5 on OSX, this isn't a problem on Safari.

**Comment by dstansby** [comment]
Firefox gives this HTML:

`<a target="_blank" href="http://www.facebook.com/143157325784718_590816757685437">
    <img class="news-source vpgnzqowdnpxasiiupqz" src="/bundles/actscamdramsecurity/images/facebook.png"></img>
</a>`

which seems odd, as it doesn't agree with what Safari is giving me, that seems to be correct looking at the actual source code.

**Comment by ajf58** [comment]
Works for me (firefox 37.0.1 on Fedora). I'll try on Windows 7 at work tomorrow. Are you able to upgrade your version of Firefox?

**Comment by dstansby** [comment]
Ah, so it turns out that they're removed (by transforming the HTML into a weird class it seems) by Ad Block Plus - I've changed the title to reflect this.

**Comment by dstansby** [comment]
https://adblockplus.org/ if anyone isn't aware of it.

**Comment by philosophicles** [comment]
So @dstansby is it actually the fault of Camdram at all? Seems like just over-eager browser extensions maybe?

**Comment by dstansby** [comment]
Indeed, I don't know, and am very happy to blame AdBlock and close this. (and disable it for camdram!)

**Comment by dstansby** [comment]
Feel free to close this, it seems that Adblock just blocks any facebook or twitter icons by default.
