### ISSUE TITLE
Sphinx index not picking up on deleted shows

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#279]
Raised in support ticket 75350 - and has previously occurred in 75225.  In the most recent case it looks like a user probably created a show (slug '2015-the-grand-duke'), someone else created a duplicate for the same show (getting slug '2015-the-grand-duke-1') then the first show was subsequently deleted.  

The issue is that both show objects come up in autocomplete search results; picking the deleted one gives a 404.

This happened in November 2014 so not a recent change.

**Comment by philosophicles** [comment]
I have not tried rebuilding the index manually to solve this particular case - think there's something that needs a more permanent fix so leaving the example in place for now.

**Comment by stumo** [comment]
Maybe a job that rebuilds the index each night?

**Comment by philosophicles** [comment]
I'm pretty sure this isn't a problem any more or it would have been reported much more recently. Closing in an effort to tidy up old stuff that'll probably never get addressed anyway. Someone feel free to reopen if they disagree.
