### ISSUE TITLE
Improve show creation to avoid duplicate shows being created

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#280]
Not too infrequently, two different people involved with one production each create a listing for it on Camdram.  Then subsequently realise the mistake and one has to be deleted.  In a few cases I'm sure we will have lingering duplicates where it was never noticed.  

Doing <something> to try to avoid this would seem helpful to end users.  It also keeps our DB tidy and avoids slugs with -1 (-2..-n) suffixes being created unnecessarily.  

This may only be possible after #42 has been implemented? (At which point there would presumably be a Show Name autocomplete that also fills in Author etc.)

Or perhaps there could be some intermediate process where the Show Name field triggers a search for exact name matches within 1 year of the current time, and (if found) presents a "Has somebody already created this show?" type warning.  User wouldn't be prevented from creating the duplicate - it's not unheard of for the same play to happen twice in one year by different societies/venues.  It would just act as a little reminder to double-check.  

Unusually, this search might actually need to include non-authorised show listings - and report who created the potential duplicate so the current user can think "oh, that person is on my production team, I should email them to check".

**Comment by hoyes** [comment]
I think we could look at the performance dates and venue too - if these match (or the performance dates are sufficiently similar or overlap or something), then we could display an error and block the creation of the show.

It could even be an error if someone tries to insert a show at with the same date/time and the same venue as another approved show, regardless of show title.

**Comment by ajf58** [comment]
I like Peter's suggestion: if another show exists (pending or otherwise) at the same time/place then prevent the user from trying to add a new show. We'd probably want to give some quite verbose feedback to the user, e.g. "Unfortunately your show couldn't be added. This could be because another show already has been approved for the same time at this venue, or another show is waiting for approval."

I've been out of touch with Camdram for a while, so I'll try to take this one on.

**Comment by hoyes** [comment]
If you haven't already found it, http://symfony.com/doc/current/cookbook/validation/custom_constraint.html is probably a nice way to do it (injecting in doctrine as a dependency to the validator service so you can search for other shows)

**Comment by hoyes** [comment]
Also (thinking some more) I don't think sample data fixture generation currently guarantees unique times at venues ...extra checks might be needed there to prevent non-deterministic errors...

**Comment by jamesterjlrb** [comment]
The other thing to watch out for is where a venue might have two shows at the same time, e.g Larkum and Main show (although larkum is normally slightly later, so this might not be relevant). It might be useful for superadmins to be able to override this warning, either for the rare case above, or if troubleshooting is required.

**Comment by philosophicles** [comment]
The Larkum is a separate venue on Camdram (as is the bar) so that should be OK.
