### ISSUE TITLE
Make URLs with slugs persistent

### ISSUE THREAD

**Issue by hoyes** [camdram/camdram#281]
At the moment, a link to a show becomes invalid if someone changes the show name. This is a problem for:
- Links in notification e-mails (e.g. if someone corrects a spelling mistake in a show name just after creating a show, the link in the approval notification e-mail will no longer work)
- SEO - maybe not a massive deal, but it means that pages in search engines' indexes suddenly disappear.

I can think of 3 possible solutions:
- Make slugs permanent (i.e. the slug is set by the initial show name, and does not change thereafter). Not great if the original show title contains a typo or something
- Store a history of all former slugs, and redirect to the most recent one. Perhaps the nicest solution, but the most work to implement.
- Change URLs to include the ID. E.g. /shows/7283/2015-rent , and if the 'slug' portion of the URL is wrong, redirect to the correct URL. A slight downside is that it's open to minor abuse, e.g.: /shows/7283/rubbish-show would redirect to the former.

Any thoughts?

**Comment by philosophicles** [comment]
The middle, most-effort solution definitely sounds best to me, but as I couldn't be implementing it I don't think you should necessarily listen to me :)

Another possible benefit of that option is that if a show is properly deleted, we could perhaps use the 'history of former slugs' approach to redirect to a slightly nicer and more specific "Sorry that show's been deleted" page, rather than the generic 404.  (I don't see that as a particularly important change but perhaps friendlier for end users.)

**Comment by philosophicles** [comment]
Alternatively, to make option 1 more palatable: could have a read-only field on the show creation screen that is populated with what the slug will be, once focus leaves the Name field.  It auto-updates if the user returns to the Name field and changes it, again when focus leaves that field. 

Add a message like "This will be part of your show's URL after creation, and then cannot be changed.  Please check your show name carefully before clicking 'Create'."

**Comment by hoyes** [comment]
https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/doc/sluggable.md is what we're currently using to generate the slugs (with a custom "transliterator" to have inserting the show year into the slug).

If I were doing it, I'd probably: 
 * Create a ShowSlug entity or something with a ManyToOne link back to a Show
 * Each time after a show is created/edited, check if the current slug is present in the slugs table, and if not, add it.
 * In getAction, if the slug isn't found in the shows table, add an additional step that looks up the slug in the slugs table, and if found, issue a 301 redirect.
 * Maybe include a created_at field to the slugs table so we can perhaps purge old slugs at some point.

The above means we always store (n+1) slugs, but I don't think the Doctrine sluggable thing above doesn't have a nice way to act upon a "slug change", so I'm struggling to think of a nice way to do it more efficiently. But if there's a way then go for it! Plus if we're going to do this, we may as well solve it more generally (e.g. if a show owner corrects more than one typo in the show name quick succession).

Maybe makes sense to do this for shows first, then roll out to societies/venues/people later once the right strategy's been figured out.

**Comment by hoyes** [comment]
Hello again...

https://www.mediawiki.org/wiki/Manual:Redirect_table might be relevant re how MediaWiki handles this.

Another way of doing it might be to have some sort of generic URL redirect table and handler, similar to https://github.com/camdram/camdram/blob/ab50748084a3bfc57e7c88f531cfbdd43a8774d2/src/Acts/CamdramLegacyBundle/EventListener/RedirectHandler.php (now deleted, but formerly existed to convert v1 URLs into their v2 equivalents).
