### ISSUE TITLE
Display the show ID in the administration box

### ISSUE THREAD

**Issue by alexbrett** [camdram/camdram#283]
Most external systems which pull data from camdram (e.g. the cast and crew display on the adctheatre.com website) use the numeric show ID in their API calls.

On old camdram, the ID of a show could be found from the show manager, whereas new camdram does not show this ID anywhere. I suggest we add this to the 'Show Administration' box shown to admins of a show.

Alternatively we could look to alter the APIs to use slugs, but this would involve coordinating with external parties (in particular the ADC website development company) so may not be practical.

**Comment by stumo** [comment]
I did a bit of research when I was making the custom api for the adc, and I
think the existing adc website can cope with slugs - however we have to do
some gueswork as to whether we are being sent a numeric id or a slug
(non-trivial, e.g. 1984). But we can probably make that work well enough.

Stuart

**Comment by sigilion** [comment]
It does show up in the json api, although that may not be useful to most people. Do we not want to discourage use of the numerical ID anyway?

**Comment by hoyes** [comment]
This relates to #281 somewhat - slugs can change at the moment.

Once #281 is implemented, old slug URLs will receive a 404 redirect to the new slug.

I'd say I'm against putting IDs on show pages though, given that they're only of interest to API users, and they are visible in the API.

**Comment by alexbrett** [comment]
The problem is the users who use the API often use it through something else. The ADC put the show id into Spektrix which is then pulled through to their website and used with the API, but the management when entering the show details have no ability to use the API themselves to get the id.

It sounds however like using the slug once #281 is fixed is probably the way forward to deal with this. I'll try and investigate what will be required here for the bits and pieces which use it at the ADC at least.

Do we know if any other users (eg I seem to recall a listings site or similar) do anything that needs the id outside of the API?

**Comment by stumo** [comment]
On 25 Jan 2015 18:38, "alexbrett" <notifications@github.com> wrote:
>
> The problem is the users who use the API often use it through something
else. The ADC put the show id into Spektrix which is then pulled through to
their website and used with the API, but the management when entering the
show details have no ability to use the API themselves to get the id.
>

I am sure I told them to 'add .json to the url and look for id.' Which I
don't consider a major hassle. Can we keep them doing that for now until
#281 is fixed? I will have a look at the custom api code this week.

> It sounds however like using the slug once #281 is fixed is probably the
way forward to deal with this. I'll try and investigate what will be
required here for the bits and pieces which use it at the ADC at least.
>
> Do we know if any other users (eg I seem to recall a listings site or
similar) do anything that needs the id outside of the API?

**Comment by hoyes** [comment]
This is somewhat idealistic (especially as it's currently broken!), but the long term solution to these sorts of use causes would be for the ADC Website to call https://www.camdram.net/shows.json?q= based on some user input, display a list of results, then store the slug in the retrieved data.

**Comment by alexbrett** [comment]
They're using old at the moment to get the ids so no urgent problem...

@hoyes its complicated by the fact the data goes into attributes in Spektrix rather than directly into the ADC site so doing lookups isn't viable. While they could do it another way, it means entering data in two places etc so not ideal...

**Comment by CHTJonas** [comment]
Old has been closed down for a few weeks now and you can get the show ID by doing an API call by appending .json or .xml to the full show slug URL. https://www.camdram.net/admin/issues/77877 would seem to imply that this is the method the theatre is using and it seems to be working fine.

I am closing in favour of  #281 as there seems to be more support in favour of the UI displaying slugs, and the API displaying IDs. Feel free to reopen if there is still support for displaying IDs user-side 😊
