### ISSUE TITLE
Make searching accent-agnostic

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#284]
Some things in Camdram have accents in their name, e.g. a person named Zoë or production of Les Misérables.  (Not that Cambridge societies are likely to get the rights for that any time soon but you get the idea.)

Very few people will bother to type in the correct accented character when searching in Camdram, but the search index does not match 'Zoe' for 'Zoë', etc. 

I believe the normal way to go about this (but think @stumo used to do this kind of thing more?) is by adding extra fields into the DB (and index for search, but never display to end-users) that store the nearest equivalent string using just ASCII a-z, A-Z, 0-9 and space.  

E.g. Zoë or Zoé would both have a plain version of 'Zoe'. 

I'm open to being told this is more trouble than it's worth :)

**Comment by stumo** [comment]
I think this can be handled database side - by setting the appropriate collation method, see http://stackoverflow.com/questions/26765434/mysql-diacritics-insensitive-search

Hopefully the framework wouldn't get in the way of this, but we'd need to test to be sure.

The advantage of doing it at the DB level is you don't have issues with edits in V1, and you don't have to double up every column you might want to search. 

Of course we might have fun getting sqlite to do the same.

**Comment by philosophicles** [comment]
Good idea - but since the search is provided by Sphinx (which has its own index outside of MySQL), does that definitely do the job? (Nudge @hoyes, when you have a moment.)

I have a vague feeling that changing the collation globally on an already-live DB isn't so easy but that might just be MS SQL (or I might be making it up).  We'd also want to check that accent-insensitive collations don't do anything wacky with newly-added accented data (I don't __think__ so) - as you say, just a question of testing thoroughly.

Another way around the V1 problem is to postpone this until we retire V1 - I don't think this is at all urgent, but would improve user experience for the rather small % of people and productions with accents.

**Comment by CHTJonas** [comment]
Bump to be considered in the context of #398

**Comment by CHTJonas** [comment]
Test case https://www.camdram.net/people/lea-de-garnier-des-garets-1

**Comment by CHTJonas** [comment]
Probably consider at the same time as #417

**Comment by hoyes** [comment]
Done: https://github.com/camdram/camdram/blob/master/tests/Functional/SearchTest.php#L223
