### ISSUE TITLE
Old venue name persists when changing an existing show's venue 

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#285]
1. Pick an existing show.
2. Note in the show summary the venue it's at ("time", "date range", at "venue").
3. Observe that the Show Admin box lists the venue as being able to edit the show (hyperlinked to the venue's page).  
3. Edit the show, and change the venue to another recognised venue. Save.
4. Observe that the Show Admin box now lists the new venue as being able to edit the show, and not the old venue. (Correct.)
5. Observe that the show summary still refers to the old venue. (Wrong)
6. Find the show in the diary - observe it still refers to the old venue. (Wrong)
7. Edit the show again, observe that the form field for the venue states the new venue. (Correct)

I cannot see where this is going wrong from a database perspective; both the 'Venue' and 'venid' fields in acts_shows are being correctly updated (but do double-check). 

This occurs for regular users who are show admins, and for super-admins. It means it's not currently possible to fully change a show's venue.

**Comment by sigilion** [comment]
This is to do with the "All performances at same venue" feature, if you switch the edit form to tour mode and fill in the individual performance spots with the appropriate venue it works fine. I'm tempted to say that we should rethink the whole single venue performance data model once we drop old, as having two different canonical locations for the performance venue to be stored is only going to continue leading to bugs like this. We could probably use some javascript to autofill the performances to simulate current behaviour.

**Comment by sigilion** [comment]
Actually four locations, given the venue/venid split on each level, but thats a separate issue.

**Comment by philosophicles** [comment]
a) I agree that once old is gone, a wider rethink of the data model is necessary (this is already on the cards).  Also grrr venid/venue split whinge third normal form grr mumble mumble. :)

b) For now, to be clear, I still think this is a bug: @sigilion's correct that you can work around this by switching to 'tour mode', but if a show is in 'single venue' mode, Camdram shouldn't ever be SELECTing from the tour-mode-related venue column(s).  Conversely, average users shouldn't be expected to work out for themselves that it needs changing in two places.
