### ISSUE TITLE
Reminder emails for unauthorised shows are broken

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#286]
Admins (of all relevant things) used to receive reminder emails for shows that weren't yet authorised, every 24 hours.

This appears to already be handled on tiberius, not antigone (@hoyes?); cron runs the following command:

    /var/www/camdram/production/app/console camdram:unauthorised-shows:email --env=prod

Output is redirected to /dev/null hence we've not been seeing the following error:

    [InvalidArgumentException]
    The directory "/var/www/camdram/20150107/app/cache/prod/jms_serializer" is not writable.

I'm not familiar enough with symfony to be confident that just chmodding that directory will solve the problem properly...

**Comment by hoyes** [comment]
I've just tried running this manually on Tiberius and got the following error:

`Call to a member function getUser() on a non-object in /var/www/camdram/20150107/src/Acts/CamdramBundle/Service/ModerationManager.php on line 155`

Looking into it further
