### ISSUE TITLE
Review ability to edit funding society after show creation

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#289]
It seems that vastly more shows these days (than 6-8 years ago) create a listing on Camdram before they know who will be funding them.

They then need to ask Camdram admins to change the Society field once funding is determined.

Regardless of why this might be, perhaps we need to make it possible for show admins to change (or propose changes to) their funding society after creation, and add some email notifications to the society admins to allow them to review/confirm this.

**Comment by dstansby** [comment]
I was just thinking this, and agree very much!

Emailing society admins with confirmation (similarly to venue/society confirmation emails for new shows) is definitely a good idea, since at the moment we're just changing the society without checking with the society.

**Comment by ajf58** [comment]
It probably is worth querying why this is happening. A first thought is that an often-used venue has gone from requiring funding to be secured beforehand to not. There's no objection, but it would be good to gauge the likelihood based on what's becoming a 'normal' workflow.

From a technical perspective I don't think it's much effort for Camdram to implement a post-update hook that:
1. Emails the previous society's admins not let them know they are no longer admins for the show
2. Notifies the society admins.

2. is a bit more interesting. I think the logic would be that if the show was authorised by a society admin, set the show as unauthorised and email the new admins, else send a notification to the old and new societys' admins informing them of the change.

**Comment by dstansby** [comment]
So I don't know how it used to work, but these days shows at the ADC and Playroom get offered a slot with no conditions on funding, and it is up to the individual shows to find funding after getting a slot. I think this means a lot of shows want to get adverts out (thus be on Camdram) before they have funding secured.

**Comment by hoyes** [comment]
Referencing #173 which details the reason why this was initially implemented - I hadn't thought of any of other the explanations mentioned.

I agree there are ways of doing it better, but I worry the logic could get quite complex quite quickly. Maybe we could allow societies that are just specified by name (i.e. not linked to a society object) to change their society or something.

**Comment by dstansby** [comment]
Alternatively, I think allowing the society to be set for the first time (not necessarily when the show is created though), but not changed once set would cover 90% of the cases we get.

**Comment by philosophicles** [comment]
Yes, that could work @dstansby.  In effect we'd recognise an allowable value of 'TBC' (whereas currently that's just freetext) and specifically permit changing 'TBC' to something else once.

The loophole @hoyes references does also need careful consideration, I think so long as all concerned admins get notified when stuff changes, it'd probably be OK.  I'm too tired to think it through right now.

This does raise the consideration that show admins can currently change the venue themselves, and arguably we should be telling the old/new venue admins about this in the same way.  Similarly a venue admin could (currently) use a similar loophole to #173 perhaps?

**Comment by hoyes** [comment]
The change above means the society field can now be changed by the show owner so long as it isn't under the control of a society that Camdram knows about

**Comment by philosophicles** [comment]
@hoyes if the show owner changes from a freetext "TBC" type value to a valid society, will the society admins get any kind of notification? As I understand it they won't, in which case I think there's an additional issue here.

**Comment by hoyes** [comment]
Fair point... reopened

**Comment by hoyes** [comment]
The above does the following upon a show being modified:
 * If the show is not yet authorised and the society or venue has changed, just retrigger the authorisation e-mail (which will now go to a new set of people).
 * If the show has already been authorised:
   * If the society has changed, and the new society is a society object, notify just the society owners that the society has changed
   * If the main venue has changed, and the new venue is a venue object, notify just the venue owners that the venue has changed

Hopefully that makes logical sense...
