### ISSUE TITLE
Broken link for adding multiple roles at once

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#290]
As a result of #109 (I believe), show pages now have a yellow message:

**New** You can now add multiple roles at once. Click here to try.

The link goes to camdram.net/shows/show-slug/many-roles which returns a HTTP error 500 page (with a 503 Service Unavailable error message right at the top of the page).  

Possibly a simple routing typo, I'm taking a quick look into this.

**Comment by philosophicles** [comment]
There appears to be no routing set up for the link's path `get_show_many_roles` to relate to `roles-new.html.twig`.  Looks like the actual controller was implemented in [this commit](https://github.com/camdram/camdram/commit/acc6cfa9d7c6fa5861cf8529dd1cc0a5777aacb5), probably just something needs adding to the relevant routing.yml?

I don't have a working dev environment at the moment (recent laptop change) so don't want to risk going further than this using GitHub's code browser...

**Comment by ajf58** [comment]
I'll try and look into this over the next couple of days.

**Comment by ajf58** [comment]
That was easier to find than I'd thought.
