### ISSUE TITLE
'Edit User' link broken (within User Admin)

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#291]
From a particular user page `https://www.camdram.net/admin/users/<uid>` - the 'Edit this user' link goes to `https://www.camdram.net/admin/users/<uid>/edit` which shows our error page.

**Comment by dstansby** [comment]
It's a "500 Internal Server Error", for reference.

**Comment by dstansby** [comment]
And possibly this is the relevant bit of the log:

> [2015-02-28 19:54:40] request.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: "Neither the property "person_name" nor one of the methods "getPersonName()", "personName()", "isPersonName()", "hasPersonName()", "__get()" exist and have public access in class "Acts\CamdramSecurityBundle\Entity\User"." at /var/www/camdram/20150225/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 367 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\NoSuchPropertyException(code: 0): Neither the property \"person_name\" nor one of the methods \"getPersonName()\", \"personName()\", \"isPersonName()\", \"hasPersonName()\", \"__get()\" exist and have public access in class \"Acts\\CamdramSecurityBundle\\Entity\\User\". at /var/www/camdram/20150225/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:367)"} []
