### ISSUE TITLE
Database setup broken

### ISSUE THREAD

**Issue by sigilion** [camdram/camdram#293]
I think 406f549582b831d1631dd05e36b2b8f389bf7979 broke the database setup in the test environment, which calls updateVenues on a show entity object.

**Comment by dstansby** [comment]
+1, just ran 
    php55 app/console camdram:database:update
and got
    > loading [2] Acts\CamdramBackendBundle\DataFixtures\ORM\ShowFixtures
    PHP Fatal error:  Call to undefined method Acts\CamdramBundle\Entity\Show::updateVenues() in /Users/dstansby/Programming/Camdram/camdram/src/Acts/CamdramBackendBundle/DataFixtures/ORM/ShowFixtures.php on line 141


                                                                                      
      [Symfony\Component\Debug\Exception\UndefinedMethodException]                        
  Attempted to call method "updateVenues" on class "Acts\CamdramBundle\Entity\Show".
