### ISSUE TITLE
Display ticket prices on show pages

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#297]
If ticket price information's been added for a show (SQL field `prices`), it should always be visible on the show's page (www.camdram.net/shows/$slug$).  

Currently it is only visible if a booking URL (SQL field `onlinebookingurl`) is also included.

**Comment by hoyes** [comment]
Do you have an example @philosophicles ? I think at the moment it doesn't display the ticket prices if there isn't also a booking url, so I'm guessing it's that, but it would be good to check there isn't something else going on.

**Comment by philosophicles** [comment]
Good point: compare www.camdram.net/shows/2015-the-grand-duke (has URL and prices) to www.camdram.net/shows/2015-midnight-cafe (prices but no URL).

I've amended the original description accordingly.

**Comment by philosophicles** [comment]
Thinking about this a bit more, I'd suggest:

* Short-term solution (if anyone can be bothered to implement) is to display price in upper-right corner where the booking link would be.  Just plain text "Tickets: £x" would be fine.
* After V1 is fully retired, potentially rework data model as each venue / performance range could have different prices (and different booking URLs), then change how this information is displayed accordingly (and in show creation/edit form).

**Comment by hoyes** [comment]
Implemented short-term solution
