### ISSUE TITLE
Venue_name blank when venue has Camdram page

### ISSUE THREAD

**Issue by chrisjamesnash** [camdram/camdram#299]
Apologies for another post, and thanks for all your help so far, but I've come across another issue when trying to get show data with a jsonp request. The venue_name field is filled normally when the venue does not have a page on Camdram (e.g. http://www.camdram.net/shows/2015-the-grand-duke), however if the venue is linked to a Camdram page the field is coming up blank (e.g. http://www.camdram.net/shows/the-mikado).

**Comment by hoyes** [comment]
Unfortunately, (as unhelpful as it is) this is a direct reflection of how Camdram's data is currently stored in the database - i.e. it either stores a reference to the venue object under 'venue' or a single name if no venue object exists.

There is a planned solution for this - to replace the 'venue' : 123 field with an sub-object containing the slug, name and a URL. I'll try and expedite getting this finished off - I've already got it working in a branch but need to tidy it up and merge it in.

**Comment by chrisjamesnash** [comment]
Ah ok, no problem. No hurry but let me know if it does get changed, thanks!

**Comment by ajf58** [comment]
Looks like this has now been implemented, albeit resulting in a slightly different JSON object schema.
For The Grand Duke:
```
other_venue: "Harrogate Theatre, Harrogate",
```
For The Mikado:
```
venue: {
id: 41,
name: "Robinson College Auditorium",
slug: "robinson-college-auditorium",
_type: "venue"
},
```
Closing as this has been implemented. @chrisjamesnash, hopefully this works well for your end use.
