### ISSUE TITLE
Sphinx search includes people with 'mapto' populated

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#303]
Searching in the main Camdram search bar shows people names that exist in `acts_people_data` where `mapto` <> 0.  

These are records that have been merged into another person record. Search should find only the "master" person record (with `mapto` = 0).

The show counts displayed against the search results appear to be correct, i.e. the master person's search result includes all shows linked to either the master or child records.

**Comment by stumo** [comment]
Would it not be better if e.g. searching for a misspelling gave you the
correct result instead?

**Comment by philosophicles** [comment]
Yeah I guess you could argue that :)

**Comment by CHTJonas** [comment]
I have just tested and cannot reproduce this issue. It's probably been resolved either by the upgrade to Elasticsearch or by commits unknown since 2015. I am going to close but please reopen if the issue still exists (I discovered #425 in the process).
