### ISSUE TITLE
People search uses slug rather than actual name

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#308]
@dtwood appears to have been playing with his Person profile again (I think) and I happened to spot this.

Searching in the main search bar for "David Wood" gets no results. Searching for "Doow Divad" does (current slug being 'doow-divad' but still with display name "David Wood").  Hope you don't mind me using this example David, please say if you do.

Sphinx should surely be using the string displayed as the person's name, rather than their slug.  Not that these will be significantly different under normal conditions, I realise...

**Comment by dtwood** [comment]
Sphinx does search by full name. My name just happens to be `[RIGHT-TO-LEFT OVERRIDE]dooW divaD[LEFT-TO-RIGHT OVERRIDE][POP DIRECTIONAL FORMATTING]`.
However, sphinx does seem to get quite confused by accents in names, for example a search for `[ACCENTED CHARACTER][SPACE]` seems to show everyone with an accented character in their name. It's then not possible to search for any of those people using their non-accented name.

**Comment by philosophicles** [comment]
Ah that makes more sense (well, sort of). 

The accent issue is #284 I believe.

@dtwood Out of interest, are you doing this for privacy reasons or just playing around?

**Comment by dtwood** [comment]
This was a "I need to do exams, so if I make it so that people can't find me to add me to shows then I can't possibly get stitched, right?"

**Comment by philosophicles** [comment]
Fair enough, I had a feeling it might be that. This feels like a potentially viable new feature so others wouldn't have to abuse the person-renaming ability, but I'm inclined to wait for some other user(s) to decide they would want it before raising an issue for it. (You're the first in my memory of Camdram to want to do that.)

I applaud your ingenuity in finding that workaround though!
