### ISSUE TITLE
Show Application Advert Not Appearing

### ISSUE THREAD

**Issue by waiwaing** [camdram/camdram#314]
Apologies if I'm missing something obvious, but the G&S Society application advertisement for "G&S West Road Show Applications" hasn't yet expired but is no longer showing on https://www.camdram.net/vacancies/applications

**Comment by dstansby** [comment]
I can see it fine (about halfway down the page)

**Comment by waiwaing** [comment]
Yep--see it now. Weird (or me just sleep-deprived :)).
