### ISSUE TITLE
Facebook open graph metadata

### ISSUE THREAD

**Issue by hoyes** [camdram/camdram#318]
I've noticed lots of these on Facebook recently:
![image](https://cloud.githubusercontent.com/assets/2594055/7920436/e80882ac-0896-11e5-9262-aae2ca62f16e.png)

I think we can make shows (and other Camdram pages) appear better in Facebook by adding special meta tags and telling Facebook what they mean:
https://developers.facebook.com/docs/sharing/opengraph/object-properties

I have access to the Camdram Facebook app - can give access to anyone interested in doing this.

**Comment by dstansby** [comment]
It doesn't look like you need any sort of access on Facebook, according to https://developers.facebook.com/docs/sharing/webmasters one can simply go to (for example) https://developers.facebook.com/tools/debug/og/object?q=http%3A%2F%2Fwww.camdram.net%2F to test a certain page.

**Comment by dstansby** [comment]
I'm also happy to have a go at this. Not sure how testing without it going live will work, apart from just checking the tags in the page source of the local test version are as expected.

**Comment by hoyes** [comment]
Hmm yea could be tricky.

If you e-mail me a public key, I could set you up with an account on Tiberius so that you can fiddle with tiberius.camdram.net ?

**Comment by hoyes** [comment]
Or alternatively, let me know when ready to test and I'll manually push to tiberius.camdram.net (it should update automatically but it's currently broken).

Re above, looking again it seems as though custom graph objects are only really useful with custom graph actions - I could think of uses (the ability to publish your involvement with a show to Facebook), but maybe overkill for this.

**Comment by ajf58** [comment]
I was thinking just the same thing last night. Go for it. You can always test that the generated output is valid HTML as a good sanity check by visiting https://validator.w3.org/#validate_by_upload

**Comment by dstansby** [comment]
I've had a start here: https://github.com/dstansby/camdram/tree/open-graph-tags

Some questions/thoughts:

- Is http://www.camdram.net/shows/{{ show.slug}} are sure fire way of getting the right URL? (I forget what the status is with permanent slugs etc.)
- The show description is a html document I think, which means getting a meaningful description (2-4 sentences) might be interesting.
- Is there a big camdram stock logo/image we could use if a show doesn't have an image?

**Comment by hoyes** [comment]
* Yes, for now (permanent slugs is currently unresolved). In twig you can do {{ url('get_show', {...}) }} in the same way as path()
 * The show description is 'Camdram markdown' - there's a 'strip_camdram_markdown' Twig filter for properly converting to text. V1 could perhaps just truncate after x characters with an ellipsis (there's a truncate Twig filter too)
 * No...but I'm currently trying to dig out the originals for Ned's graphics...

**Comment by philosophicles** [comment]
Re: bullet 2, in the longer run we could look at changing the show creation page to have a separate "short description" type field, as well as the main description.  Such a bit of text is often created for other marketing purposes anyway.

This might actually be a good thing for other places, I guess - if we had it we might find other uses for it. (E.g. hoverover text on the diary page?) 

In any case, users aren't always good at writing the 'description' field as solely a description of the show - I often see descriptions that meander into production planning details, audition details etc. So I don't advise trying to pick any part of it out for a Facebook link.

**Comment by hoyes** [comment]
It doesn't look like I have a bigger logo than the one logo already in the repository.

@ewaquekett do you still receive notificaitons from here? For this (and future reference) It would be great to know the name of the font you used for the Camdram logo if you still have the originals.

**Comment by hoyes** [comment]
Looking at your repo @dstansby , I think the meat tags ought to go inside <head></head> somewhere

You'll probably need to add somthing like `{% block metatags %}{% endblock %}` to the base template (https://github.com/camdram/camdram/blob/master/app/Resources/views/base.html.twig) which you can then override in child templates

**Comment by dstansby** [comment]
Thanks for the replies, I should have fixed everything mentioned now. The last thing I think I need is the facebook app ID (see here: https://developers.facebook.com/docs/sharing/webmasters#markup , og:app_id)

**Comment by hoyes** [comment]
The app ID is 464689303574287

I've added you to the Facebook app in case you need anything else

**Comment by dstansby** [comment]
Great, I think this is ready to be tested. The code is here: https://github.com/dstansby/camdram/tree/open-graph-tags and is up to date with master.

**Comment by hoyes** [comment]
I've merged this in and included so this is now on www.

Looks like the object validator's complaining about the fact that image urls are relative without the domain name ...will probably need a change to the image bundle to fix. Facebook proper actually works OK though because it seems to go and scrape the image still as it did before. Also seems to complain when there's no image present so we probably ought to put something there...

Also, wondering whether there are other pages we could add these tags too - people, societies and venues would probably make sense.

**Comment by ajf58** [comment]
I have some other questions about artwork that @ewaquekett may be able to help with. Is that the only thing that is keeping this issue open?

**Comment by hoyes** [comment]
We need to make the image urls absolute. At the moment it outputs:
      <meta property="og:image" content="/images/973943cc9bfd24526d9ce17a4a6b2c60_w1024_h768.jpeg" />

This requires a small modification to https://github.com/camdram/symfony2-image-manager to make a twig function that outputs an absolute url.

The above fails Facebook's validation tool, but in practice it works OK because Facebook's algorithm manages to find and use the image on the page. Ought to fix properly though.
