### ISSUE TITLE
Cannot add roles to shows

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#319]
Trying to add any roles (cast, band or crew) to a show (any show), via "single row" or multi-role add screen, leads to a server error.

The main text reports Error 500 whilst a pop-up bar along the top reports Error 503 Service Unavailable.

Adding roles via Camdram V1 still works.

**Comment by philosophicles** [comment]
Various changes to show page were made in the most recent release so I guess we need to start there...?

**Comment by hoyes** [comment]
My bad - this only applies to adding a role for a *new* person, and after refactoring I only tested with an existing person.

**Comment by hoyes** [comment]
Will push this out tomorrow night

**Comment by dstansby** [comment]
Fixed?

**Comment by hoyes** [comment]
Oops yes - closing

**Comment by ajf58** [comment]
I'm wondering if this is involved in #333
