### ISSUE TITLE
Make camdram-users Google Group into an embedded 'forum'?

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#321]
Another idea/discussion point. Google Groups can be embedded into websites and used more as a forum/discussion board than a group email list (https://support.google.com/groups/answer/1191206?hl=en). 

Should we do that? (Other forum engines are available, of course, but we're already using the Group.)

The current Contact Us page perhaps offers too many choices / is too hard for most users to decide which contact medium is best for them. Partly, this might be because the existence of the Group primarily as an email address they can email, overlaps a lot with the existence of websupport@camdram.net that they can email as well. 

Putting the emphasis on the web-page side of the Group might make things clearer - this could be a 'Forum' link in the top black bar perhaps? 

Then again, I'm not sure the concept of a forum/discussion board is still familiar to current undergrads; I might be showing my age! ;-)

**Comment by philosophicles** [comment]
(Doing this wouldn't stop people from getting emails every time a post was made to the Group, of course.)

**Comment by CHTJonas** [comment]
I am closing as consensus seems to be to move away from Google groups and stick with Brimir for support email, and Gitter for dev chat.
