### ISSUE TITLE
Broken application link on show page

### ISSUE THREAD

**Issue by hoyes** [camdram/camdram#324]
https://www.camdram.net/shows/2015-quinoa-a-fry-tfully-middle-class-sketch-show

links to

https://www.camdram.net/vacancies/applications/2015-quinoa-a-fry-tfully-middle-class-sketch-show

which gives a 404 error

**Comment by ajf58** [comment]
Works for me, albeit with a 302 (found). Hrm...

**Comment by hoyes** [comment]
Closing given we can't reproduce it
