### ISSUE TITLE
schema.org structured data markup

### ISSUE THREAD

**Issue by hoyes** [camdram/camdram#328]
Schema.org has structured data specs for the 4 'core' Camdram data types, which I think we could add without much effort:
 * Shows: https://schema.org/Event
 * People: http://schema.org/Person
 * Venues: https://schema.org/Place
 * Societies: https://schema.org/Organization

Prompted by @stumo's post to webteam about https://github.com/Southbank-Centre/OpenEvent, which has a very similar data model to Camdram.

**Comment by philosophicles** [comment]
Similar data model to ours, but I would add "much-simplified" - at least as-yet, they have none of our vacancy-related objects for example. Definitely one to watch, perhaps also to get in touch with?

**Comment by ajf58** [comment]
Worth looking at http://stackoverflow.com/questions/6402528/opengraph-or-schema-org as well.

**Comment by ajf58** [comment]
I've added a block of mark up to the various items as per the commit message. The complete schema.org markup is [huge](https://schema.org/docs/full.html) and runs the risk of taking us down a rabbit hole for unknown benefits. Labelling up our events should hopefully mean we get some rich search results in Google.

Does anyone else want to see more markup? We could reasonably add this to a person, including marking up his/her [Role](https://schema.org/Role) or [PerformanceRole](https://schema.org/PerformanceRole). Thoughts?

**Comment by philosophicles** [comment]
Thanks for this one @ajf58, I also reckon the commit above will be a really tangible benefit in search results. 

My first thought is that enrichening person search results is very significant in a different way - people might have much stronger feelings about their own search results than about any show, society etc. I think most would be very positive, but some might object (strongly) on privacy grounds? 

I'm working partly on the assumption that enriched search results would look vaguely like what I see if I search for, for example, Ian McKellen.

**Comment by philosophicles** [comment]
One option might be to call this issue closed, and open a new one for person markup, which we intentionally leave until a later point and/or openly invite opinions on.

**Comment by ajf58** [comment]
Let's close this one for now. I agree that there is a risk of "too rich" a search result. I guess the hope we have here is we achieve nice results for things like searching for "Cambridge Shakespeare" and so on, which we should get from these enhancements. Even better will be if we get rich search results displayed in Google similar to "vue Cambridge cinema"
