### ISSUE TITLE
Autofocus breaks mobile scrolling

### ISSUE THREAD

**Issue by waiwaing** [camdram/camdram#329]
So I hate to complain about a feature that I requested in the first place (https://github.com/camdram/camdram/issues/310), but the autofocus on the search breaks scrolling on mobile (at least on iOS). The focus doesn't happen until the user scrolls, which then scrolls the viewport to the top of the page (whereas the user was scrolling down), and brings up the keyboard. You then have to dismiss the keyboard and rescroll, which is annoying.

I haven't had time to actually investigate, but I suspect what's happening is that the JS that selects the first form field when the search isn't there might be the bit that's breaking it.

**Comment by philosophicles** [comment]
I have also been finding autofocus a bit annoying on some non-homepage pages, e.g. /admin/issues/$number and /contact-us, where the first form field is a long way below the top. 

Wondering if this should be limited to just the homepage while we're revisiting the feature...?

**Comment by hoyes** [comment]
I've reverted this feature everywhere for now given it seems to be causing issues (no nice way to just do it on the home page)
