### ISSUE TITLE
Inconsistent email bounce processing (into websupport system)

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#330]
I'm not totally sure what's going on here or what's causing this, but it looks like we're handling email bounces inconsistently.

For examples visible to Camdram admins, see support issues 75835 vs 75836. Both relate to the same show and as far as I can tell are bounces from the same non-existent email address (a graduated cam.ac.uk address). 

The first (35) is a bounce (it's come from our ISP's mailer-daemon email address) but doesn't include any information about what email address bounced; the second (36) has full information about the bounce, the email address that couldn't be found, and all information from the mail host that handles the email domain. (mx.cam.ac.uk in this case). 

This discrepancy isn't the end of the world but the second format is much more useful for preventing repeat bounces, e.g. by removing a user with bouncing email address from soc/venue admin status.

**Comment by Cam** [comment]
Hi @philosophicles could you please remove the `@cam` in your above issue. It's messing up my comment tracking 😆 Thanks!

**Comment by philosophicles** [comment]
Looks like @hoyes got there first (ta!). Apologies!

**Comment by CHTJonas** [comment]
Closely related to #387.

**Comment by CHTJonas** [comment]
@alexbrett do you have any insight into this? It's such a long time ago that it might just be better to close in favour of #387...

**Comment by GKFX** [comment]
Closing this as so much has changed about our email infrastructure since the issue was reported; also all the bounces I've seen in recent times have been of the latter, more useful sort anyway.
