### ISSUE TITLE
Add captcha to public-facing contact forms

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#331]
Based on support ticket 75847 it seems a spambot has found our contact form for (anonymously) contacting the administrators of a society/venue (/societies/society-slug/contact). 

It looks like this might already have led to Yahoo (at least) blocking mail from our domain. (Worse case, it might be all mail via our ISP's mailserver - @alexbrett FYI).

We should probably put captchas on these contact forms, and on the main /contact-us one as well. (Any others?)

**Comment by hoyes** [comment]
This sounds concerning.

There *should* be a captcha if you're logged out, and there should also be one on the create account page. I suppose once you've created an account there's nothing stopping you from spamming.

I'm working this weekend so have limited time available, but if I cnlant find another loophole I'll put the captcha back for everyone.

**Comment by philosophicles** [comment]
Have checked - I do get the captcha when logged out (normally never fully logged out!), sorry I'd forgotten it was login-dependent. 

So not quite sure how ticket 75847 has arisen, perhaps take a look at that first and see if you make a different conclusion to me? :)

**Comment by hoyes** [comment]
I have a slightly longer look at this last night and what intrigued me was that the "From:" line had a name, but no e-mail address. This alone might have been sufficient to trigger Yahoo's spam filters.

I discovered last night that there's currently no server-side checking of the e-mail address field, so it is possible to submit with no e-mail. This obviously needs fixing, but they'd have still would have needed to get past the captcha, which seems to be working correctly.

Given that if you are logged in it always takes the email from your account, I strongly suspect it was sent by a logged-out user/bot, and that they found a way to circumvent the captcha. I guess captchas aren't 100% infallible...

We should probably have better logging of the contact forms too, as at the moment it's not easy to tell whether this is the first time such an e-mail has been sent or the seventieth.
