### ISSUE TITLE
Wackiness with 'Add Multiple Roles' page

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#333]
Support ticket 75891 reports that 'Add Multiple Roles' (shows/slug/many-roles) isn't working. I agree, having just tested this. The page itself displays fine, but clicking Add Roles then leads to the standard Error 500 page. 

As far as I'm aware this was working for at least a while after the feature was added (see #109 and #290) so it's probably a more recent commit that's caused this. (But this may be my imagination.)

I haven't thoroughly poked into why but my gut feeling is that it'll be related to the following oddity on the same page, which should probably be fixed anyway so might as well get tackled first to see if it is the cause of above. 

* There's variation between shows as to whether the page includes a pale-yellow Show Administration panel at the top. E.g. [2009 Macbeth](https://www.camdram.net/shows/2009-macbeth/many-roles) does not, but [2006 Macbeth](https://www.camdram.net/shows/2006-macbeth/many-roles) does; [2014 Macbeth](https://www.camdram.net/shows/etg-2014-macbeth/many-roles) does not but [a random other current show](https://www.camdram.net/shows/2015-depths-of-their-heart/many-roles) does. 
* Where the Show Administration panel does exist, within 'Add Multiple Roles' pages exclusively, it seems to always refer to a totally different, seemingly unrelated show. In most cases it refers to shows by one particular improvised-comedy society, but not always one particular show, compare the 2006 Macbeth above with [2007 Macbeth](https://www.camdram.net/shows/2007-macbeth/many-roles) and the random happening-at-time-of-writing show above.  I've not found any examples where it isn't a show by that society.  In the case of one show that incorrectly pops up against many others, it itself [references a different show](https://www.camdram.net/shows/2007-the-ice-crystal-maze/many-roles).  
* In such cases all links within the admin panel refer to the incorrect (improvised) show slug, so following them would take the user to a totally different show (assuming they had admin rights for both). 

Note, the links above will only work if you have admin rights for the shows in question, or global admin rights.

**Comment by ajf58** [comment]
Thanks for a very detailed bug report. I'll be honest I've not looked at Camdram for a fair while, but it'd be good to fix this close to the start of term.

**Comment by philosophicles** [comment]
I have hardly been giving it much/any attention recently either, so no criticism etc at all on that front!

**Comment by ajf58** [comment]
So when I tried to replicate this by impersonating the user who raised this issue the logs showed this:

```request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Catchable Fatal Error: Argument 1 passed to Acts\CamdramBundle\Controller\Show\RoleController::addRoleToShow() must be an instance of Acts\CamdramBundle\Controller\Show\Show, instance of Acts\CamdramBundle\Entity\Show given, called in /var/www/camdram/20150605/src/Acts/CamdramBundle/Controller/Show/RoleController.php on line 170 and defined" at /var/www/camdram/20150605/src/Acts/CamdramBundle/Controller/Show/RoleController.php line 187 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 1 passed to Acts\\CamdramBundle\\Controller\\Show\\RoleController::addRoleToShow() must be an instance of Acts\\CamdramBundle\\Controller\\Show\\Show, instance of Acts\\CamdramBundle\\Entity\\Show given, called in /var/www/camdram/20150605/src/Acts/CamdramBundle/Controller/Show/RoleController.php on line 170 and defined at /var/www/camdram/20150605/src/Acts/CamdramBundle/Controller/Show/RoleController.php:187)"} []```

So this leads me to think that it's related to bb4a18c4, which was part of a larger refactoring effort. The function definition is fairly basic:
```
private function addRoleToShow(Show $show, $role_type, $role_name, $person_name)
```
This function is now a directory deeper than it once was, so it's looking for a show entity in the wrong place, I think. I'll try and look into this a little further over the next couple of evenings, but I think the next step is getting my development environment back up to speed.

**Comment by ajf58** [comment]
My change in b4a75ac only corrects the ability to add multiple roles.

The random admin block is definitely a separate issue. There random shows has suspciously year-like values for their id field. For example:

2006 Macbeth is showing The ICE Chromosome (acts_shows.id = 2006)
2015-depths-of-their-heart is showing The ICE Crystal Maze (acts_shows.id = 2015)
2007-the-ice-crystal-maze is showing Pulp Improv (acts_shows.id = 2007)
as is 2007-macbeth

So it looks like the resource id field (rid) that's used for one of the queries is getting set to the year the show is in, but I think we need to have a bit more of a dig around to see exactly how this is happening.

**Comment by ajf58** [comment]
Now fixed. @hoyes, what are your thoughts about rolling out a release?
