### ISSUE TITLE
File not found in autocomplete results

### ISSUE THREAD

**Issue by dtwood** [camdram/camdram#336]
The bottom three autocomplete results for pirates are for shows that don't exist when you click them.

**Comment by ajf58** [comment]
IIRC there's a period update to the search results. I'm not sure what causes entries to be purged. We can discuss this at Friday's social.

**Comment by hoyes** [comment]
There *should* be a process that runs every night at 4am - I'll check this
evening.

It's quite dumb - it dumps the whole index and rebuilds it again from the
DB so any deleted shows *should* get removed.

**Comment by ajf58** [comment]
This is a transient issue, where a show has been deleted in the previous between 4am and the time of searching for this term. Resolving as won't fix.

**Comment by TheMadProff** [comment]
Unfortunately this issue doesn't appear to be resolved - I can still see those Pirates entries...

**Comment by philosophicles** [comment]
Yep, I agree - reopening.

**Comment by philosophicles** [comment]
I've just checked the DB directly via SQL and the slug 'the-pirates-of-penzance' definitely doesn't exist in acts_shows. So these are either failing to get purged (having previously existed), or getting magicked up from somewhere else...

**Comment by CHTJonas** [comment]
This appears to no longer be the case - I can't find the shows referred to. With #398 we transitioned to Elasticsearch with improved removal of entities from the search index when they are deleted. As such I am going to close acknowledging that the search index can become poisoned with old entity data for at most 24 hours, however this is actually now quite unlikely.
