### ISSUE TITLE
Venue assigned yet displayed as "Venue to be confirmed"

### ISSUE THREAD

**Issue by stumo** [camdram/camdram#340]
http://www.camdram.net/shows/2015-improvengers-assemble Currently is listed as "Venue to be confirmed" although when you edit it it is correctly set as "Corpus Playroom" (and saving does not update this.

What I believe happened is the show was initially created without a venue, then edited to add a venue. (Based on emails I received 23:33 on 2/11/2015). We seem to have updated the venue in some but not all places.

We'll want to fix the updating code to ensure all shows have the correct venue on them - but possibly also fix any in the database that have got into this state.

**Comment by ajf58** [comment]
Performances have their own concept of venue, to allow a show many performances to occur in multiple places. In this case the performance had no link to a venue. Creating a new performance automatically links it to the venue when possible.

To solve this we'd need to update all performances for a show that matched the old value for venue. Pseudo SQL update acts_performances set venid = $new_venid where sid = show.id and venid = show.venid

I'm not sure how easy this is to implement, or how valuable.

**Comment by CHTJonas** [comment]
I am unable to reproduce this issue despite trying many combinations & permutations of creating new shows and performances with venues either set or not. As I don't recall recently hearing about this issue amongst the student user base, or seeing any support tickets I am going to mark as closed.
