### ISSUE TITLE
Make plain text format views of vancancies

### ISSUE THREAD

**Issue by ajf58** [camdram/camdram#342]
In response to issues with using v1 to generate the content of CUADC mailing lists, let's simply consider .txt to be a first class citizen for the various vacancy types.

**Comment by ajf58** [comment]
This is a first pass, and took longer than I'd hoped. Curiously we don't display a "show week" for any vacancies, so currently the leap needs to be made using either the diary page. It looks like this has  resulted in people changing how they use, with show auditions having to explicitly add this to their audition text (see [Murmering Judges](https://www.camdram.net/vacancies/auditions#2016-murmuring-judges), [The Beck](https://www.camdram.net/vacancies/auditions#2016-the-beck) for examples).

We should really add this key feature back in, but it seems the logic is complicated. To me I'd like to add a method to a Show entity so that I can get its performance weeks as a string (this is an attribute of a show, and the method does the work), However, it seems that to do that I need to use the "week manager" service, which in the Symfony world is a Bad Thing (apparently). I am also a little suprised that we are using records in the database for defining week numbers: the rules are well defined [here](https://www.cam.ac.uk/about-the-university/term-dates-and-calendars).

**Comment by philosophicles** [comment]
I think V1 originally had the termdates database table so that, if the rules ever changed in the future (you never know...), it wouldn't have to impact the past. I imagine @hoyes implemented the V2 solution partly because of how V1 did it..? I've never stopped to work out whether those rules (i.e. the Uni Statues & Ordinances) fully define when Full Term starts or whether there is a bit of flexibility over which Tuesday is chosen in some years. Either way, I don't think there's any harm in using a table for this, it should in general be more performant than working it out on the fly, no?

**Comment by ajf58** [comment]
Yup. I'm more focused on what's the best approach to getting shows labelled with their weeks. It's such a shame we can't get users to engage more.

**Comment by ajf58** [comment]
So I think the best think to do is to extend the WeekManager service with a function that takes a show and returns the performances as a string. I'm pretty confident it's a service, based on my understanding of the Symfony literature, but I'm canvassing for opinions.

**Comment by hoyes** [comment]
My suggestion would be to:
 * Add something like getWeeksForShow(Show $show) to WeekManager, which just returns an array of weeks
 * Add a non-persistent property to the Show entity (i.e. protected var, getter, setter but no Doctrine annotations)
 * Add "WeekManager" as a dependency of ShowListener, and create a method there which injects a show's weeks to the object after Doctrine loads a Show object
 * Create a Twig function which takes an array of Weeks and outputs something in nice English like "Weeks 1-2" or "Weeks 1 and 3" etc

**Comment by hoyes** [comment]
Yes, I stored it in the database (albeit generated automatically from a script based on the University's rules you describe) because in theory it could change...although the logic has stayed the same for all of Camdram's history at least...

There were also ideas at one point in time about trying not to make the codebase too Cambridge-specific, in case other universities/communities wanted to re-use our open source code, so I refrained from baking the mechanics of Cambridge term dates too deep.

**Comment by hoyes** [comment]
On the wider point - this seems like a good idea. Once the API's finished I was thinking of adding some icon links someone on each page show all the other representations available (i.e. "JSON", "XML", "iCAL", "RSS") in a standard, so we could add a "TXT" icon too to give it more visibility.

I'm not sure whether adding term/week names should block this though...we should definitely do it but not sure whether it needs to be on the "v1 switch-off" critical path if it's going to difficult to do quickly.

**Comment by ajf58** [comment]
Looks like we're on the same ish page here. I'll be able to push something in the next hour.

**Comment by ajf58** [comment]
Oops, 30d8931 broke regression for shows without any performances. I'll fix that.

**Comment by ajf58** [comment]
I think that's everything for this issue. I'll remove the in-progress tag in a moment, and then leave it for a bit for everyone to have a look at. If after that we're happy then let's close the issue and try and push this to the live site over the holidays.

**Comment by ajf58** [comment]
What was the regression, @hoyes?

**Comment by hoyes** [comment]
JSON/XML output of shows and auditions etc (there should probably be some tests for this...)

$this->render() is a core Symfony method which bypasses the "ViewListener" which produces the JSON/XML output. I changed it to use $this->view(), which is part of the FOSRestBundle - the output of this function is a "View" object which is detected by the "ViewListener" which transforms the data into JSON/XML as required.

As you obviously discovered, $this->view(...) doesn't allow you to send additional data to the template, so I moved the logic for getting week info into ShowListener, so it automatically injects the week info into a Show object whenever one's loaded from the DB.

**Comment by ajf58** [comment]
There's a couple of snags I'd like to fix before closing this issue:

1. [ ] Correct rendering of term dates that span multiple terms. e.g. "The Cambridge Footlights International Tour Show 2016 (Easter Week 6 to Week 0)" should be "Easter Week 6 to Michaelmas Week 0".
2. [ ] Unlike the other views, the [auditions plain text](https://www.camdram.net/vacancies/auditions.txt) page doesn't include the table of contents that's at the start of the other two views.

Once I've tweaked these then I'll close this. It does mean we'll do another release.

**Comment by hoyes** [comment]
Cool. I can see there being another release next week sometime.
