### ISSUE TITLE
Create FAQ page

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#343]
Aim is just a static page - to sit alongside 'About', 'Development' and 'Contact Us'. Text needs prettifying, I might do this if I have time but feel free to go first. 

Initial topic ideas (credit mostly @hoyes and @ajf58):

* What is and isn't appropriate to list on Camdram - might need to be some iterations on this to reach a consensus as it's never been crystallised into words, but "Cambridge student theatre, and anything else likely to be of significant interest to users who are expecting a Cambridge student theatre focus" is a good start.  See first para of http://old.camdram.net/infobase/camdram/events.  Enumerating some examples of "okay" and "not okay" might be good. 
* How do I add a show / event? 
* Can I buy tickets for x?
* I've got a great new script, would you like to buy it?
* My name is misspelled, can you change it for me?
* I'm listed on Camdram under two different names, can you fix this?"

Other questions can be added over time. 

Bonus points for referencing this page somehow from other contact points, so people are prompted to check FAQs before sending an enquiry that is answered there.

**Comment by ajf58** [comment]
There's the bare bones, feel free to add to this. I agree that we should agree on the wording for the "what's suitable" section.

**Comment by ajf58** [comment]
This has been implemented, so closing. I think we can just add more FAQs as we go.
