### ISSUE TITLE
Fix PHP 7 and Symfony 3.0 incompatibiles

### ISSUE THREAD

**Issue by hoyes** [camdram/camdram#347]
Camdram currently fails in PHP 7 because of a bundle we're using which includes a class name which matches new a reserved identifier in PHP 7:

https://travis-ci.org/camdram/camdram

Symfony 2.8 logs all deprecated calls in the dev toolbar. At the time of writing the home page has 263 references to deprecated parts of Symfony 2.8, which will be removed in Symfony 3.0

**Comment by ajf58** [comment]
Related?
```
$ php app/console server:run
PHP Fatal error:  Class 'AppKernel' not found in /home/andrew/public_html/camdram/app/console on line 20
PHP Stack trace:
PHP   1. {main}() /home/andrew/public_html/camdram/app/console:0

Fatal error: Class 'AppKernel' not found in /home/andrew/public_html/camdram/app/console on line 20

Call Stack:
    0.0002     235712   1. {main}() /home/andrew/public_html/camdram/app/console:0

PHP Fatal error:  Class 'Symfony\Cmf\Component\Testing\HttpKernel\TestKernel' not found in /home/andrew/public_html/camdram/vendor/symfony-cmf/tree-browser-bundle/Tests/Resources/app/AppKernel.php on line 6
```

**Comment by hoyes** [comment]
Potentially... something similar happened to me after updating to Symfony 2.8 in composer.json, which I thought I'd fixed by adding:

    "classmap": [ "app/AppKernel.php", "app/AppCache.php" ]

to composer.json

Have you tried manually deleting the cache (`rm -rf app/cache/*`)........

**Comment by ajf58** [comment]
I've managed to get things going again, but had to back out some local modifications. Ah well.

**Comment by hoyes** [comment]
Sorry to hear that...let us know if you know which steps fixed it...

**Comment by dstansby** [comment]
I've just tried reinstalling my local copy of camdram, but I'm getting the following error which is probably related to this issue?
```
$ php55 app/console camdram:database:update --verbose
Dropping database schema...
Database schema dropped successfully!
ATTENTION: This operation should not be executed in a production environment.

Creating database schema...
Database schema created successfully!
  > loading [1] Acts\CamdramBackendBundle\DataFixtures\ORM\SocietyFixtures
PHP Fatal error:  Call to undefined function Symfony\Bridge\Doctrine\Logger\iconv_strlen() in /Users/dstansby/Programming/Camdram/camdram/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/Logger/DbalLogger.php on line 102
```

**Comment by hoyes** [comment]
Looks like "iconv" is now a required package in Symfony 2.8...I'll update the README.

Does `sudo port install php55-iconv` help?

I get another error on my checkout unrelated to this too, which I'm guessing you'll get after clearing the error above. I'll commit something which hopefully fixes that problem in a second...

**Comment by hoyes** [comment]
Fixed that above...let us know if you have any further issues

**Comment by dstansby** [comment]
Yep, seems to have worked! I'm now getting what looks more like an actual camdram codebase error :)

**Comment by hoyes** [comment]
Awesome - if you pull changes hopefully that error will go away....

**Comment by hoyes** [comment]
For the record, looks like iconv is pre-compiled into PHP on Ubuntu nowadays, so have just updated the README for Macports. @ajf58 I can't find any convincing info this for Fedora - don't suppose you could check and update the README if required when you get a sec.
