### ISSUE TITLE
Show and venue API examples are broken

### ISSUE THREAD

**Issue by rob-eager** [camdram/camdram#349]
- [ ] Show examples just need updating to the new show slug style starting with a year rather than ending in a number.
- [ ] Current venue examples aren't in the www.camdram.net/venues list so don't return anything

**Comment by hoyes** [comment]
Cheers Rob. My comments on #24 about the current status of the API were sparked by this... we're still happy for people to use it for the time being but it comes with a "may break without warning" flag while we figure some things out.

Closing this ticket to keep API discussions in one place, although this comment should create a reference to this ticket and the issues mentioned on #24.
