### ISSUE TITLE
Mobile site: top linkbar not visible

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#354]
Viewing Camdram on Chrome for Android (Android 4.x): the top linkbar does not make links to 'About', 'Development', 'FAQ', and 'Contact Us' visible. 

The black bar itself is still present, with 'Create an account' and 'Log in' links.

**Comment by ajf58** [comment]
Also an issue on Chrome v47.0.2526.83 on Android 5.1.1 (visit chrome://version in the browser for this info). As per the [wiki entry](https://github.com/camdram/camdram/wiki/Software-stack) we use various bits to do the heavy lifting of cross browser/screen type support, most notably HTML5 Boilerplate and Foundation. Neither have really kept pace with the state of the art (our version of Foundation is two major versions behind, and HTML5BP has also gone up a major version). It's been on my low priority TODO list to bring these up to date, but I've worked on assumption that it wasn't broken so didn't need fixing.

I'm not saying that if we update our frameworks it'll all be fixed, but it seems like a good excuse to do so, see what things look like and go from there

**Comment by hoyes** [comment]
To be honest, this was how it came out the first time I tried it on a mobile, couldn't think of a way of neatly adding the links back (not enough horizontal space, having a second sandwich icon might look odd), so just omitted left it as it is in the knowledge that the links are in the footer at least. 

I.e. this isn't a regression, but not much thought was put into it at the time either.

Picture below for reference:
![image](https://cloud.githubusercontent.com/assets/2594055/12054325/a655d910-af1a-11e5-9a40-1e78f035ae04.png)

**Comment by philosophicles** [comment]
I concur with @ajf58's suggestion of updating the frameworks as a first step. 

Being honest, my personal preference would be to get all the actual page links onto the same (lower) linkbar, so the top one would just be log-in related. Then the existing mobile sandwich icon would do everything. This makes more sense to me as there's nothing inherently different about the pages on the top linkbar, from a simple end-user perspective. 

I'm not sure if it'd work to simply append the 'About', 'Development', 'FAQ' and 'Contact Us' links - think that might be too much horizontally even for a desktop version. I do have some ideas of how I'd reorganise to make it work with fewer links overall; not sure if this is the right place for them though they're inspired mainly by user questions we've had on the Google Group etc.

**Comment by ajf58** [comment]
I think we've always gone with having the "generic" website items in the top row, and site-specific things in the lower row. Personally I like this split: all sites have an About, FAQ, login page, and these are also largely static. The lower row is links to all of the interactive/dynamic content.

**Comment by philosophicles** [comment]
That does also make sense :) This is clearly highly subjective so whatever is minimal effort should win out.

**Comment by philosophicles** [comment]
Just checked today on a modern Android Chrome browser (Android 7) and this is still the case.

**Comment by philosophicles** [comment]
I feel like 'About' and 'Contact Us' are both pretty important to include on smaller screens - it's entirely possible that a new Cambridge student's first ever visit(s) to Camdram will be on small screens (I can't check how this looks on a tablet e.g. 7" or 10" screen...). 

Similarly, anybody could browse to the site on their smartphone having never heard of Camdram and want to know at least broadly what the site is - the About page would be one they might seek out. 

Not everyone will remember our websupport email address all the time; a regular site visitor on mobile might find a problem and want to tell us about it right then, but need to check what the email address is. We want to encourage that as otherwise they might never tell us about the problem! (I am fairly sure quite a lot of websupport incoming email is written on mobile devices - I see "Sent from my iPhone" and similar signatures quite frequently.)  I know we also have the email address at the bottom of the screen but it doesn't make so explicit _why_ to contact that email address... I feel like having a clear "Contact Us" link and page is also useful. 

The same arguments can definitely be made, slightly less strongly, for the FAQ. Dev/API pages less likely I feel, but if we're making three out of five work...

**Comment by philosophicles** [comment]
That all said, I also don't know what the right (or indeed, any) UX solution to this would be. We would probably have to deviate a little more from the big-screen design - e.g. somehow present all pages (these static ones, and the dynamic ones) from a single sandwich icon when the screen size is small.
