### ISSUE TITLE
Societies page - separate section for inactive societies?

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#359]
Just an idea - perhaps we could/should create a third section at the bottom of the Societies page for ones that are (probably/definitely) inactive. 

This would keep the content people are most likely to be looking for at the top. We could have a static sentence at the start of the Inactive Societies list, explaining why they're there and encouraging people to contact us if we're wrong.

Exact definition of inactive is up for discussion but I'd suggest "no Camdram show records for future shows nor any shows in the past year".

A fair number of matching societies were probably one-off things unlikely to ever be restarted, but sometimes societies are revived after quite a long gap so I'm loathe to delete them. Camdram is an important part of the collective memory for this, and perhaps even might encourage a society to be revived.

**Comment by ajf58** [comment]
It's definitely possible. I guess the approach would be to add an "isActive" method to the Society entity. In pseudo SQL your most recent show is "select from shows where socid = x order by id desc limit 1" and then as you say you can then check if the first performance date is > now - 1 year. The Society controller should then do the work of splitting the results of "findAllOrderedByCollege" into groups that can be used by the template. I think...

**Comment by ajf58** [comment]
Scratch that. If we just use the affiliation of a society then this is much simpler. We'd need to decide periodically if a society is no longer affiliated with Camdram, but then it's all a lot simpler.

**Comment by philosophicles** [comment]
Related to #431 and #346... 

Above I suggested that the definition of an inactive society would relate to future and recent past show activity. 

However, it could (also / instead) relate to presence of verified admins. A society could be, by definition, inactive, if there are 0 society admins with verified email addresses.... this could possibly simplify the logic of those other issues. 

Combined with #346, this could essentially force people who want to add a show against Revived College X Theatre Society (after a spell of 4 years where the society got forgotten by the college JCR etc), to contact us and get some up-to-date admins assigned to the society before they can submit the show listing. I think this would be a good thing. Currently I think we have some societies that go under the radar a bit, being active in real life but having no Camdram admins, and the real-life committee submit listings and just let the site admins authorize them for a longer period of time. 

Just a thought @hoyes @CHTJonas @GKFX

**Comment by GKFX** [comment]
Yes, I think that sounds like a good idea. However it might be necessary to add a disclaimer of sorts to the inactive section. Broadly along the lines of:
>## Inactive societies
> We've lost contact with these societies and aren't aware of any recent activity by them. If you're part of one of them, and it's becoming active again, please [contact us](#).

rather than asserting that the society is definitely inactive just because we've lost contact.

**Comment by philosophicles** [comment]
Heartily agree with that suggestion @GKFX. I've been thinking for years that we need a call-to-action like this somewhere, but I couldn't figure out where or what it should look like...
