### ISSUE TITLE
PHP Notice: Undefined variable: ace in /var/www/camdram/20151223/src/Acts/CamdramSecurityBundle/Security/Acl/AclProvider.php on line 191, referer: https://www.camdram.net/shows/2016-bugsy-malone/admin/edit

### ISSUE THREAD

**Issue by ajf58** [camdram/camdram#364]
This needs investigating.

**Comment by GKFX** [comment]
I haven't tested, but by inspection of the code this was fixed in https://github.com/camdram/camdram/commit/4ab5a804981e603376255fb383cafac240facced.
The (former) line 191 is inside an `if ($persist)` loop, and `$persist` is now true if and only if `$ace` is non-null.
