### ISSUE TITLE
Techies RSS feed yields HTTP 500

### ISSUE THREAD

**Issue by waiwaing** [camdram/camdram#365]
Attempting to access http://www.camdram.net/vacancies/techies.rss gives an HTTP 500. This does not happen with either the actors' or the directors/producers' rss feeds.

```
> GET /vacancies/techies.rss HTTP/1.1
> Host: www.camdram.net
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 500 Internal Server Error
< Date: Mon, 02 May 2016 06:24:30 GMT
< Server: Apache/2.2.16 (Debian)
< X-Powered-By: PHP/5.4.45-1~dotdeb+6.1
< Cache-Control: no-cache
< Vary: Accept-Encoding
< Connection: close
< Transfer-Encoding: chunked
< Content-Type: application/rss+xml
< 
```

**Comment by ajf58** [comment]
From Symfony's log file 
```[2016-05-03 22:53:57] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Unable to find template "ActsCamdramBundle:TechieAdvert:index.rss.twig"." at /var/www/camdram/20151223/vendor/symfony/symfony/src/Symfony/Bridge/Twig/TwigEngine.php line 128 {"exception":"[object] (InvalidArgumentException(code: 0): Unable to find template \"ActsCamdramBundle:TechieAdvert:index.rss.twig\". at /var/www/camdram/20151223/vendor/symfony/symfony/src/Symfony/Bridge/Twig/TwigEngine.php:128, Twig_Error_Loader(code: 0): Unable to find template \"ActsCamdramBundle:TechieAdvert:index.rss.twig\". at /var/www/camdram/20151223/vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/Loader/FilesystemLoader.php:91, InvalidArgumentException(code: 0): Unable to find template \"ActsCamdramBundle:TechieAdvert:index.rss.twig\" : \"Unable to find file \"@ActsCamdramBundle/Resources/views/TechieAdvert/index.rss.twig\".\". at /var/www/camdram/20151223/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Templating/Loader/TemplateLocator.php:81, InvalidArgumentException(code: 0): Unable to find file \"@ActsCamdramBundle/Resources/views/TechieAdvert/index.rss.twig\". at /var/www/camdram/20151223/app/bootstrap.php.cache:2566)"} []```

Indeed we don't have an index.rss.twig, but there is an [rss.html.twig](https://github.com/camdram/camdram/blob/master/src/Acts/CamdramBundle/Resources/views/TechieAdvert/rss.html.twig). This has been the case for a long time, according to git, but this is consistent with [Auditions](https://github.com/camdram/camdram/tree/master/src/Acts/CamdramBundle/Resources/views/Audition), and [Applications](https://github.com/camdram/camdram/tree/master/src/Acts/CamdramBundle/Resources/views/Application).

I think the next step is to see why the routing is incorrect for the techie adverts. Some regression testing might stop this happening in the future.

**Comment by ajf58** [comment]
Another brain dump:
For Auditions and Applications it looks like the annotation to the Entity is being picked up, but not in the case of the TechieAdverts. I think pinning down why that's gone amiss would be the way to fix this. Any thoughts, @hoyes ?

**Comment by hoyes** [comment]
It was because the controller was doing $this->render(...), which directly renders a template instead of $this->view(...), which sends the response to the FOSRestBundle multi-format view system. The RSS format is controlled by an annotation on the TechieAdvert entity.
