### ISSUE TITLE
Increase character limit of techies' advert "extra details" field?

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#369]
The following would be an extremely trivial change technically speaking (edit line 122 in `camdram/src/Acts/CamdramBundle/Entity/TechieAdvert.php`, the Doctrine annotation stating `max=1140`) but I want to canvass opinions. 

A show has recently hit the character limit for this field - they have a large number of positions to fill, and wanted (reasonably I think) 4 or 5 sentences about each to explain the role and ideal applicant. 

The corresponding database field is a `longtext` which can hold 4 GiB of text - definitely way more than 1140 characters even allowing for potential weird extended Unicode. So we could change this. 

Pros
- More flexibility for shows, no need to rely on hosting additional details outside Camdram

Cons
- Increased DB size / disk requirements, if somebody really went to town
- Vast amounts of text isn't likely to get read by most people, especially without additional formatting
- Shouldn't actually _break_ the site but wouldn't exactly look nice
- Syndicators of our data, e.g. email lists, might want shorter text themselves

Despite this unbalanced list I actually do think we should increase the limit - not insanely but maybe to 8000 characters. 

Please comment with any opinions. If no-one objects in the next week or so, I will change it.

**Comment by ajf58** [comment]
I think it seems ok to me to increase this. I imagine our disk usage is probably becoming increasingly dominated by the use of posters/images on show pages nowadays (which is not a bad thing).
