### ISSUE TITLE
Unable to create account

### ISSUE THREAD

**Issue by falcoso** [camdram/camdram#374]
Whenever I click on create account on the camdram page it goes straight to '400 Bad Request'

**Comment by philosophicles** [comment]
Hi @falcoso, thanks for reporting this. I've just tried this myself and it works fine for me, so this might have been a temporary glitch. Could you try again and comment if it's still a problem? 

If it is still a problem, it may help to know what OS/platform and what browser you're using.

**Comment by falcoso** [comment]
Hi its all sorted now thank you!
