### ISSUE TITLE
Mobile bug / spam thing

### ISSUE THREAD

**Issue by huskydog** [camdram/camdram#375]
Hey there,

I have no coding knowledge, so no idea what the actual problem is, but when browsing camdram on mobile it seems to want to ping the user to a bunch of spammy websites -- thing 'ASDA prize draw' / 'Horny Singles' kind of sites. A friend and I have both experienced it, so it seems to be something to do with the site, as opposed to a locally infected device?

But yeah, in summary: odd bug which seems to ping users (on mobile only, as far as I can tell) to spammy sites.

**Comment by hoyes** [comment]
Thanks very much for reporting this. @dtwood has managed to find the root cause of this in pull request #376, which is now merged and live so hopefully this is now fixed.
