### ISSUE TITLE
User merge tool failing with Symfony error

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#377]
Unable to merge two users currently. Symfony error log shows: 

>  request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedMethodException: "Attempted to call an undefined method named "getAuthorisedShows" of class "Acts\CamdramSecurityBundle\Entity\User". Did you mean to call "getAuthorizations"?" at /var/www/camdram/20170630/src/Acts/CamdramAdminBundle/Service/UserMerger.php line 53 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedMethodException(code: 0): Attempted to call an undefined method named \"getAuthorisedShows\" of class \"Acts\\CamdramSecurityBundle\\Entity\\User\".\nDid you mean to call \"getAuthorizations\"? at /var/www/camdram/20170630/src/Acts/CamdramAdminBundle/Service/UserMerger.php:53)"} []

Having inspected the User class, the "did you mean" hint appears entirely correct.

**Comment by philosophicles** [comment]
Have committed a simple correction to UserMerger.php as suggested by the error log. 

However, it seems to me that `User.getAuthorizations()` is returning a collection of instances of class `Authorization` (rather than a collection of `Show`s). UserMerger.php goes on to call setAuthorisedBy() method, which exists for `Show` but not for `Authorization`. 

So unless there's some inheritance going on that I can't see, or some other magic, I think UserMerger.php will now error on line 55 rather than 53. I'm less sure how to fix that appropriately; I _think_ it's correct for us to be working with a collection of `Authorization`s not `Show`s, but perhaps Shows would be more correct. Or, `Authorization` needs a new method?

@ajf58 or @hoyes, or anyone else - able to help out here? This is about as far as I can go alone (and I hope I've gone in the right direction).

**Comment by philosophicles** [comment]
Following a new release to prod incorporating the above fix, can confirm user merge still not working. Haven't dug into error messages yet.

**Comment by hoyes** [comment]
8dc5c2d6429bfc33c194d0b8bc6eec258db2a347

**Comment by hoyes** [comment]
Apologies for missing this back in July @philosophicles  . Your change was correct but there were unfortunately lots of other errors below that due to various changes to the User entity fields that hadn't be tracked through to UserMerger. In the commit above I've changed to use reflection to figure out the associations more dynamically and added some tests.

Will probably do another release push sometime between Xmas and new year so can perhaps keep ticket open until you've been able to test on www.

**Comment by philosophicles** [comment]
No worries at all @hoyes (and merry Christmas!). I suspected as much - thanks for sorting it out. I will review and close/comment next time I see a release.

**Comment by hoyes** [comment]
Believed to be fixed in release 20180118... reopen if there are still issues.
