### ISSUE TITLE
Edit Society page does not retrieve existing Facebook event/page info

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#380]
This is slightly related to #339 in that it's also a refinement to Camdram<>Facebook interaction, but this is a fairly isolated bug. 

Steps: 
1. Find a society that doesn't currently have a link to a Facebook page. 
2. Edit Society and add a Facebook page identifier/slug. For URL `https://www.facebook.com/mypage/` I had entered `mypage`. Click save. 
3. Observe the Camdram society page now has the Facebook post box and link to the Facebook page. Observe that in the database `societies` table, `facebook_id` is populated correctly. 
4. On Camdram again, click to edit the society again. 
5. Bug: observe that the `Facebook event/page` field is empty. It should be populated with some meaningful string relating to the Facebook page (as discussed in #339, exactly what that string should be is up for some debate).
6. At this point the `facebook_id` column is still populated correctly, and if you now leave the edit society page without saving, the Facebook integration remains working. However, if you click Save on the edit page (with or without making any other changes), the `facebook_id` column is nulled out and the Facebook page integration is lost.

**Comment by hoyes** [comment]
Should be fixed in release 20180128
