### ISSUE TITLE
old.camdram.net HTTPS certificate expired

### ISSUE THREAD

**Issue by ojno** [camdram/camdram#382]
Could someone please renew the certificate for old.camdram.net HTTPS? This does get used for ADC ticket sales authentication, and possibly other things.

(The current cert, with SHA1 04:68:8C:BA:69:C9:4A:44:21:96:50:5D:38:AD:6D:F0:7F:DA:9C:36, expired on Wed 29 Mar 2017 05:27:55 GMT.)

**Comment by philosophicles** [comment]
Heartily agree, please let's not keep on flogging the dead horse any longer if we can avoid it. 

@ojno, do you know who is responsible for maintaining this ADC Ticket Sales thing? (I don't actually know what it is, think it's more recent than me.)

**Comment by hoyes** [comment]
ADC room booking and ticket sales are now migrated to www.camdram.net, so I'll consider this fixed
