### ISSUE TITLE
I am both preparing for and currently on Porterhouse Blue

### ISSUE THREAD

**Issue by GKFX** [camdram/camdram#384]
I [http://www.camdram.net/people/george-bateman] have a role in Porterhouse Blue, which has a Saturday matinee. My profile lists me as currently involved with and also preparing for it, which I presume shouldn’t be happening.
I’m wondering if this is because the 7:45 runs have started but the matinee is yet to be performed.

**Comment by philosophicles** [comment]
Thanks for reporting, @GKFX. 

This behaviour is controlled by [camdram/src/Acts/CamdramBundle/Entity/ShowRepository.php](https://github.com/camdram/camdram/blob/master/src/Acts/CamdramBundle/Entity/ShowRepository.php), functions `getCurrentByPerson` and `getUpcomingByPerson`. 

I'm just interpreting the ORM-y query builder back into SQL to understand their logic.

**Comment by philosophicles** [comment]
So I think the intended date logic for these functions looks like:

- **Past:** latest performance end date before today (not including today)
- **Current:** show (not performance) start date before today and end date on or after today
- **Future:** earliest performance start date after today (not including today)

I think the immediate problem here is a SQL logic bug on line 132 of `ShowRepository.php` in `getUpcomingByPerson` (and also symmetrically on line 167 in `getPastByPerson`): 

```
->groupBy('s.id')->addGroupBy('p.start_date')
->having('MIN(p.start_date) >= :now')
```

By grouping the result set by start_date, the `MIN` function within subsequent `having` clause doesn't have the desired effect - the expression within the MIN function shouldn't be part of the `group by` list. 

Other observations about this:
- We're using the performances table for past and future functions but not for current. We should probably be consistent across all three functions? (I.e. use the exact same basic SQL query set, and just apply different constraints.)
- I think our current-show set logic has a gap as well: a show that starts today is apparently not included in any of the three function results. (The show in question, Porterhouse Blue, starting on Tuesday 6th Feb but seemingly not being listed on @GKFX's page as "currently involved with" until the server time reaches midnight on 7th Feb. Unless I've got my SQL logic wrong!)

**Comment by philosophicles** [comment]
A simple change so far but I've opened a PR in case anyone wants to align the way the three functions work, with or without the `performances` table. I'm not clear on whether we need to use it at all in this context.

**Comment by philosophicles** [comment]
This should be fixed when the next release happens.

**Comment by GKFX** [comment]
Observed again for e.g. https://www.camdram.net/people/isadora-dooley-hunter on https://www.camdram.net/shows/2018-the-pirates-of-penzance-at-the-minack on 14 September, i.e. before the performances had started.
