### ISSUE TITLE
500 Error getting .json on some shows

### ISSUE THREAD

**Issue by stumo** [camdram/camdram#392]
Camdram support issue 77877 reveals that we're giving 500 errors when viewing some shows as .json - when .xml works fine.

I have been able to find a few shows where json works - e.g. http://www.camdram.net/shows/2018-after-juliet.json - but there are many where it doesn't - http://www.camdram.net/shows/2018-snow-orchid.json http://www.camdram.net/shows/2018-lover-boy.json

**Comment by hoyes** [comment]
Fixed in release 20180307
