### ISSUE TITLE
Drop database tables/fields only used by v1

### ISSUE THREAD

**Issue by hoyes** [camdram/camdram#395]
Placeholder for discussing this in more detail.

Will need to be slightly judicious until room booking and support e-mails are migrated but I suspect there are already a number of things that could be removed.

If/when I get time, thinking of putting the current SQL schema in a Google doc so we add comments and track changes etc.

**Comment by CHTJonas** [comment]
I believe this is on hold until the mail handling PHP is rewritten/upgraded from V1?

**Comment by hoyes** [comment]
I think we can call this done really. I had to manually restore an empty acts_pages table on Tiberius to make the email handler work, so we just need to remember to manually delete that when we're done with v1 (#263).

I sort of jumped the consultation I described above, so feel free to shoot me for that... In the end it was pretty obvious what could go and what couldn't (basically everything in CamdramLegacyBundle). More invasive database changes (e.g. #159 will need more discussion anyway).
