### ISSUE TITLE
Rethink search backend

### ISSUE THREAD

**Issue by hoyes** [camdram/camdram#398]
We currently use Sphinx for the search index, backed up by https://github.com/camdram/sphinx-realtime-bundle.

The custom Symfony bundle used by this has become a bit of a maintenance burden over time so I think some sort of more major change is required. Possibilities:

 * https://github.com/FriendsOfSymfony/FOSElasticaBundle seems to be the most actively maintained Symfony search integration, but has previously been rejected because of concerns over Java's memory usage. We could maybe reevaluate this in 2018, and maybe do a shoot-out or something
 * See if someone else has made a Sphinx-based integration in the intervening years which we can adopt
 * It might be possible to make some simplifications by folding the separate repository into the Camdram repo and paring down the functionality to what's actually needed to minimally interface with Sphinx.
 * Engage with whoever runs FOSElasticBundle and see if they're interested in supporting Sphinx as a backend option. The SphinxRealTimeBundle was original based on that but it's probably diverged over the years.

Also, we currently have additional code that allows Sphinx searches to be swapped out with a direct database query, the idea being that it might be helpful for new developers or if we have to take Sphinx down in production. In hindsight though, it would probably be simpler to make search-related functionality "Sphinx or nothing", and just make the site behave elegantly if Sphinx is not available. I think the database-based codepath has regressed over the years to be point where it still requires Sphinx to be present anyway.

**Comment by hoyes** [comment]
I'll move all the Sphinx code in-bundle and pare it down to what's actually necessary. Will do this in a branch as it'll likely be a bit messy.

**Comment by hoyes** [comment]
As a starting point, I'll move all the Sphinx code in-repo and pare it down to what's actually necessary. Will do this in a branch as it'll likely be a bit messy.

**Comment by hoyes** [comment]
I'm swinging back towards https://github.com/FriendsOfSymfony/FOSElasticaBundle for this, as the bundle is very nice, seems to integrate with Camdram very easily (as the Sphinx stuff was originally based on that) while allowing us to delete a lot of code and has other nice features too (such the ability to create separate namespaced instances for different instances of the site on Tiberius, and fuzzy autocomplete matching).

I'm going to plough ahead with this in a branch, then probably set it up on a subdomain on Tiberius along with Elasticsearch to see what we think before merging it in.

**Comment by CHTJonas** [comment]
To be honest, Elasticsearch seems to be the way that most projects and sites are heading/headed. Hopefully the performance overheads of running a Java search engine have reduced a bit as you say @hoyes.

**Comment by hoyes** [comment]
That's good to know. Sounds like Elasticsearch is almost certainly the "right" answer for this - we just need to manage the roll out and tweak the settings if necessary.

**Comment by CHTJonas** [comment]
@hoyes is this largely now complete and ready for closure or is there still work to do? 😃

**Comment by hoyes** [comment]
There are still some issues for sure... but I guess the initial implementation is complete and the issues can be fixed on the relevant tickets. Closing.
