### ISSUE TITLE
Separate Dev/Staging DB

### ISSUE THREAD

**Issue by CHTJonas** [camdram/camdram#400]
Assuming DB resource usage is cheap, I propose that we setup a seperate staging database for the Camdram dev environment. This would function entirely like normal except that we could create test shows/societies/people that don't affect our main production instance. We could then setup a cron task at say 3am each day to drop the entire contents of the staging DB and then copy the prod DB into staging, to keep it up to date but still separate from prod.

**Comment by hoyes** [comment]
As an open source project, there's a separate but related need to provide useful data for development purposes without breaking GDPR. There's a load of stuff at the moment to automaticaly make seeded random fictional test shows etc for development purposes which at one point in time was used on the checkout being served at http://tiberius.camdram.net/ too but I keep resuing that domain for other purposes... 

Wondering whether it makes sense to use the same set of data for both, or maybe I'm creating a problem that doesn't exist.

An alternative might be to create some method of sufficiently anonymising a Camdram DB for public consumption. Or having splitting the DB into public/private parts and doing different things for each...

**Comment by CHTJonas** [comment]
Maybe an idea for the future would be to repurpose Antigone (with a fresh clean OS) when we finally decommission the box? We could have Antigone serving a totally separate development environment that we can give trusted people access to but which only has dummy seed data (so no GDPR concerns). Then Tiberius can be reserved purely for the prod environment and email relaying.

Would this be useful or do people tend to use a local web server on their personal machines?

**Comment by hoyes** [comment]
I personally develop on a local web server. The two server solution was meant to be a very temporary thing while we do the v1/v2 transition...

Way off topic, but had pondered about Docker-ising Camdram to make setting up a dev environment much easier, which could maybe be used on Tiberius too. I think Windows 10 / Hyper-V makes this more widely available than last time this sort of thing was discussed.

**Comment by CHTJonas** [comment]
Where is the code that generates the seed DB data? I had a search but I can't seem to find it! 😳 

At the moment Camdram seems very fragile to be containerised IMO but maybe it's a goal for the future at some point!

**Comment by hoyes** [comment]
I've just restored https://development.camdram.net/ to its former "glory". Still lacking a commit hook but it's at HEAD at the time of writing...

Could still be changed in any number of ways, but thought I'd at least demonstrate the status quo.

**Comment by CHTJonas** [comment]
Ok so that's just a manual checkout into `/var/www/camdram/dev`? Looks like we just need to setup a deploy key from GitHub and maybe a helper script or similar 📝 

Would this use the camdram UNIX user account or a separate `github-deploy` user? Just wondering what is best security practise.

**Comment by hoyes** [comment]
Yep manual checkout at the mo. Was just thinking about this as well.

I'm kinda inclined to use https://docs.travis-ci.com/user/notifications/#Configuring-webhook-notifications as opposed to a Github hook. Introduces a bit of delay but should filter out breaking changes and have a side effect of debouncing multiple successive commits.

I'm liking the idea of a github-deploy user part of the camdram group, rather than adding www-data to camdram. Struggling to think of a simple way of forwarding the webhook though...

**Comment by hoyes** [comment]
https://github.com/adnanh/webhook looks interesting...

**Comment by hoyes** [comment]
Webhook is now in place for development.camdram.net

Went with a Github hook in the end (there are fewer examples on the Interwebs for Travis...)

**Comment by GKFX** [comment]
development.camdram.net is working great now with automatic deployment so I'm going to close this.
