### ISSUE TITLE
API Permissions out of Scope

### ISSUE THREAD

**Issue by CHTJonas** [camdram/camdram#402]
1. User email addresses can be read by API client applications even without the `user_email` OAuth2 scope being requested.
2. Setting any scope with `write write_org` included seems to generate "an unsupported scope was requested" error.

I'm going by the API scopes as detailed in [authorize.html.twig](https://github.com/camdram/camdram/blob/master/src/Acts/CamdramApiBundle/Resources/views/Authorize/authorize.html.twig).

**Comment by hoyes** [comment]
1. should now work (on master.dev)
2. turns out I'd implemented it as `api_write` and `api_write_org` in the codes/tests but `write`/`write_org` in the authorize.html.twig template. It's now `write`/`write_org` everywhere
