### ISSUE TITLE
"Can my society be added to Camdram?" FAQ entry contradicts actual policy

### ISSUE THREAD

**Issue by GKFX** [camdram/camdram#405]
FAQ says:
> ## Can my society be added to Camdram?
>
>Probably, yes. We're not trying to be exclusive - just ask us. As well as being on the main list of societies, this will allow people to choose your society when creating new shows.

But when people ask us, we say that you need to list some shows first. As such, the entry should probably be updated with our actual policy.

**Comment by philosophicles** [comment]
Just to explain roughly why it is how it is now (but not to justify/defend it - it can of course be changed): the intention was to keep the FAQ answer brief, vague and positive to encourage people to contact us and open a discussion where more nuance and case-by-case specifics can be handled. Plus, most of all, just to send the message that the list of societies is not static, nor chosen by some secret cabal (a 'wait to be invited' scenario). Which I think there's a slow tendency for people to start assuming over time, if these things aren't explicitly stated. 

Presenting too rigid or official-sounding a policy might put people off ever asking us - which is not desirable. It's not a lot of extra effort for show creators to enter the society in freetext, but it creates extra admin burden and decreases data quality in one sense.

If things like "you need to list some shows first" were to be added, I'd recommend still trying to hit a "well.. it depends...usually... generally" type tone - take for example the idea of a society that only produces one (large) show per year.

**Comment by CHTJonas** [comment]
I'd support a slight rewording with the implication that people can & should freely ask us to be added, and the idea that we're not trying to be exclusive remains.

**Comment by GKFX** [comment]
Remaining open is important; I just dislike having to say no to people who reasonably believed from the FAQ that we would list their society. How does this strike people?
> ## Can my society be added to Camdram?
>
>Probably, yes. We're not trying to be exclusive, but we want to avoid listing societies that exist only briefly for a single show. As such, you should generally get in touch with us once there are a couple of shows on Camdram supported by your society, and we'll then create a society page for you. This is very much flexible, so please do feel free to ask.
