### ISSUE TITLE
Remove redundant fields on contact forms for logged in users

### ISSUE THREAD

**Issue by hoyes** [camdram/camdram#406]
At some point in the past, contact forms (both the main "Contact Us" page and the individual show/society contact pages) omitted the name, e-mail and Captcha fields for logged-in users. Would be nice to restore this.

**Comment by CHTJonas** [comment]
Was this because it takes the name and email from the user's details? In which case maybe we can just pre-fill those fields from what we know them to be?

**Comment by hoyes** [comment]
Yea pre-fill would work too. Very minor but seems a bit redundant to ask people to type them in again.
