### ISSUE TITLE
Production Log Files not Rotated

### ISSUE THREAD

**Issue by CHTJonas** [camdram/camdram#408]
A quick _find_ on Tiberius suggests we have circa 1G of log files. We should probably look at adding the following to logrotate, both for our own sanity and to save disk space.

```
sudo find / -xdev -type f -size +1M -name "*.log" -exec ls -lah {} \;
-rw------- 1 camdram camdram 22M Jun 16 23:14 /home/camdram/procmail.log
-rw-rw-r--+ 1 pah58 camdram 70M Jun 18 18:00 /var/www/camdram/shared/logs/prod.action.log
-rw-rw-r--+ 1 pah58 camdram 623M Jun 18 17:06 /var/www/camdram/shared/logs/prod.log
-rw-rw-r--+ 1 pah58 camdram 188M Jun 16 16:20 /var/www/camdram/shared/logs/dev.log
-rw-r----- 1 root camdram 8.5M Jun 18 18:12 /var/log/apache2/camdram_prod.log
-rw-r----- 1 root camdram 3.0M Jun 18 18:13 /var/log/apache2/other_vhosts_access.log
-rw-r--r-- 1 root root 129M May 28 19:49 /var/log/pidstats.log
-rw------- 1 root root 2.3M Sep 20  2014 /var/log/searchd/query.log
```

Does anyone see any reason to keep historic log files more than about 60 days? This could also relate to GDPR compliance as I seem to recall that puts a limit on the time we are allowed to keep information (ie. date/time/IP address/URL of a users' request).

**Comment by hoyes** [comment]
Sounds like a very good idea. 60 days sounds fine.

**Comment by CHTJonas** [comment]
I have added a `camdram` file in the logrotate configuration directory which would now take care of this.
