### ISSUE TITLE
Search API returns errors

### ISSUE THREAD

**Issue by CHTJonas** [camdram/camdram#409]
The search API returns HTTP 500 errors. For example:

https://www.camdram.net/search.json?q=Fitzwilliam
```
{"error":{"code":500,"message":"Internal Server Error"}}
```

https://www.camdram.net/search.xml?q=Fitzwilliam
```
<?xml version="1.0" encoding="UTF-8" ?>

<error code="500" message="Internal Server Error" />
```

**Comment by hoyes** [comment]
I'll look at this as part of #398

**Comment by CHTJonas** [comment]
This is fixed in the latest checkout: https://development.camdram.net/search.json?q=david
