### ISSUE TITLE
API responses for a multi-venue show

### ISSUE THREAD

**Issue by CHTJonas** [camdram/camdram#411]
An API get request to a show with multiple performances at different venues returns a response that lists venues by their `other_venue` field. For example in the case of https://www.camdram.net/shows/1997-api-test-the-second.json:
```
{
    "start_date": "1997-01-01T00:00:00+00:00",
    "end_date": "1997-01-01T00:00:00+00:00",
    "time": "1970-01-01T09:30:00+01:00",
    "other_venue": "ADC Theatre",
    "_type": "performance"
}
```

I think it would be much more useful if this returned a response with a JSON venue object, hypothetically for example:
```
{
    "start_date": "1997-01-01T00:00:00+00:00",
    "end_date": "1997-01-01T00:00:00+00:00",
    "time": "1970-01-01T09:30:00+01:00",
    "venue": {
        "id": 29,
        "name": "ADC Theatre",
        "slug": "adc-theatre",
        "_type": "venue"
    },
    "_type": "performance"
}
```

The reason for this suggestion is that it enables further details about the venues to be looked up since you have the venue slug for a subsequent get request. This isn't an issue with shows at single venues.

**Comment by hoyes** [comment]
https://development.camdram.net/shows/the-king-and-i.json

The venue is now exposed for each individual "performance" for a single venue show now too, but hopefully isn't too big a deal - that's kinda just what the data model happens to be at the moment.

**Comment by CHTJonas** [comment]
If each show has singly or possibly multiple performances which themselves now contain a venue that is always returned, is it worth removing the venue field from the show itself?
