### ISSUE TITLE
Security considerations for specifying API access token

### ISSUE THREAD

**Issue by CHTJonas** [camdram/camdram#415]
Currently, to make an authenticated API call you send an appropriate request to a URL endpoint with the OAuth2 access token set in an appended query string. This means that access tokens show up in browser histories and server logs, for example:
```
GET /auth/account.json?access_token=lotsofentropy HTTP/1.1" 200 4011 
```

Unless their is some precedent for the way we're currently doing it, I believe it would be best security practice to move away from appended query strings to either HTTP headers or POST parameters. This would be a very drastic change and would definitely break backwards-compatabiltiy, but I think it's _potentially_ a bit dangerous and definitely worth discussion even if we decide not to change anything. And maybe we could have a transition period where we support both query strings or method Y?

More information on why this is not ideal: https://blog.httpwatch.com/2009/02/20/how-secure-are-query-strings-over-https

**Comment by hoyes** [comment]
This is the implementation we're currently relying on: https://github.com/FriendsOfSymfony/oauth2-php/blob/master/lib/OAuth2.php#L546

So the headers or POST methods should already work. Ideally I guess https://github.com/FriendsOfSymfony/FOSOAuthServerBundle would provide an option to disable access_tokens as URL params but I can't find anything relevant their issue tracker or oauth2-php above...

**Comment by CHTJonas** [comment]
Fab thanks @hoyes! It does work as you suggest and as detailed in http://tools.ietf.org/html/draft-ietf-oauth-v2-bearer-04#section-2.1. If/when some proper API documentation gets written we can include elements of this discussion. For the time being, I'll make sure new room booking uses headers.

Tested as working:
`curl --header "Authorization: Bearer lotsofentropy" "https://www.camdram.net/auth/account.json"`

There are a few public APIs that allow use of query strings so as long as we give people the option of query string/header/post data I would think that would be fine.
