### ISSUE TITLE
Make search insensitive to punctuation

### ISSUE THREAD

**Issue by CHTJonas** [camdram/camdram#417]
Searching for "winters" doesn't match any search entities such as "The Winter's Tale", presumably because of the apostrophe.

Interestingly, a similar search for "midsummer nights" returns a single result but with an apostrophe?

**Comment by CHTJonas** [comment]
This is still a bug with the latest upgrade to ElasticSearch, for example: https://development.camdram.net/search?q=sadlers versus without the final "s" on the end.

**Comment by hoyes** [comment]
Sadler's wells still works above + tests at https://github.com/camdram/camdram/blob/master/tests/Functional/SearchTest.php#L198
