### ISSUE TITLE
Redirect from object's id to slug

### ISSUE THREAD

**Issue by CHTJonas** [camdram/camdram#419]
In v1 `micro.php` allowed redirection from an object's id to it's canonical page (the URL with the slug in it). We should probably re-introduce this into all the relevant controllers for example:

- /shows/by-id/1234.json -> /shows/year-name.json
- /venues/by-id/1234.json -> /venues/name.json
- /societies/by-id/1234.json -> /shows/name.json

There may be other objects I'm missing where this might be useful too.

**Comment by hoyes** [comment]
Implemented for shows, societies, venues and people. Can be seen at https://development.camdram.net/shows/by-id/26.json
