### ISSUE TITLE
Search only indexes the first 50 characters of a show title

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#429]
This show exists (and is not new):
https://www.camdram.net/shows/university-of-cambridge-asia-theatre-tour-2017-time-of-my-life

Searching in the search bar for `Time of My Life` does not find any results - either in the instant results or if I hit enter to the separate search results page. This is a bug because the above show should be found! 

Searching for `2017: ti` does still find the above show, but searching for `2017: tim` no longer finds it. So this appears to be because only the first 50 characters of a show title are being indexed? 

This show's title is much longer than most, but not ridiculously long. Unless extending the index length would really impact performance, I'm in favour of indexing the whole show title.

**Comment by CHTJonas** [comment]
Interesting that the colon seems to matter here too (which is #417). `2017: ti` works but `2017 ti` doesn't.

**Comment by CHTJonas** [comment]
Also tested as a bug searching for `Cambridge University Charity Fashion Show (CUCFS) 2018`

**Comment by hoyes** [comment]
Looks like this is an Elasticsearch default (https://www.elastic.co/guide/en/elasticsearch/reference/5.6/search-suggesters-completion.html#completion-suggester-mapping).

Could maybe just bump that parameter, but given the other open tickets the Elasticsearch config probably needs looking at again.

**Comment by hoyes** [comment]
Should now be fixed - added test above. The 'edge_ngram' filter requires an explicit maximum, so it technically isn't gone completely but I've raised it to 255 (https://github.com/camdram/camdram/commit/a97444194290abd18c7fb4c4accd3ca77bd82f2b#diff-a6e6a86ff889d9f6ea7b525797f8ec7eR20). Can always raise further if there are still issues.
