### ISSUE TITLE
Add ability to create and edit generic events

### ISSUE THREAD

**Issue by zzaanna** [camdram/camdram#432]
Hello! Do you consider it worthwhile to create a section for **Workshops/Talks**?

I imagine workshops'll be added in a similar way like shows with properties: **Title, Workshop Leader, Date and Time, Venue, Category, Society, Description, Fee/Membership Requirement**(if any), **External links**, etc. And can be recurrent or one-off.

There has been a growing trend for societies to organize various workshops/talks for acting and production this year and they've all been quite popular. Exec Committee is also looking to do more "Skill Share" Workshop by either students or alumna in the future and there certainly will be lots of workshops targeted at freshers in Michaelmas. However there isn't a centralized place for all the information and it could be quite troublesome to track them down on Facebook. I feel the new section will hopefully make workshop information more accessible/visible to theatre community and encourage societies to do more workshops.

What do you think? Cheers!

**Comment by hoyes** [comment]
Hello! By chance, this was also recently discussed as an aside on #320 (scroll down to the bottom) so this definitely something we'd like to support, but I don't think anyone had actually created a ticket so thanks for creating it!

The thinking to date has been to make a slightly more generic "events" feature that can additionally support things such as Fresher's squashes, AGMs etc without any additional effort, so the fields would probably be:
 * Title
 * Description (which could contain details of the leader, membership requirements, external links)
 * Venue
 * Society (optional)
 * Date and Time

A minimal version of this would probably allow society admins to create events without admin approval (similarly to shows). It might also be nice to allow non-soceity admins to submit events for admin approval, but that's a bit more work. There was actually something very similar to this in the previous version of Camdram, and the database table still exists but we never got around to adding the UI in this version...

Would something like that be sufficient for workshops, or would there be benefits from having a more specialist section?

**Comment by zzaanna** [comment]
Sounds really sensible!

**Comment by hoyes** [comment]
That's great :+1: I've just changed the ticket title to match the more generic version of this.

You'll see above that we have over 80 open tickets to try and prioritize at the moment and limited developer resource so it's hard to say when this will be implemented. If you have any technical inclinations and fancy helping with this then let us know and someone can point you in the right direction!

**Comment by philosophicles** [comment]
Similar functionality suggested in support ticket 2494 recently
