### ISSUE TITLE
Improve ordering of full search results

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#439]
This is possibly a regression introduced by the move to ElasticSearch - I have a vague feeling we did something like what I describe with Sphinx, but I could be wrong. 

See https://www.camdram.net/search?q=Cambridge+Shorts for example: all the search results are shows and all have exactly the same title, so at least in this case I'd definitely expect to see the newest show at the top and so on backwards in time. 

I appreciate the effective result order is probably also highly affected by the search engine's weighting/ranking of "best" match, which is fine - but not sure it's really ideal in this case. (If I was ranking these similar shows by "best" match alone, I'd probably include the ones with the string `Cambridge Shorts` in the description above those that only have it in the title - but that isn't happening.)

For Camdram's purposes, recent or future time-bound things are generally going to be better matches than older time-bound things. So the reverse date ordering makes more general sense too. It's easy for shows; people do also have some time-binding (most recently-active date); shows and venues could also be time-ordered by recency of a show linked to them, I guess. 

I haven't played with the search extensively so I don't know if there's also any alphabetic ordering or anything else going on - those things might also need consideration, though I think chronology is probably the most important factor besides general search engine result ranking.

**Comment by hoyes** [comment]
This was an unintended regression in the Elasticsearch migration... should now be fixed https://github.com/camdram/camdram/blob/master/tests/Functional/SearchTest.php#L269
