### ISSUE TITLE
Improved DB+filesystem backups

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#440]
Leaving this one intentionally vague as a placeholder; this came up in an email discussion back in February (@hoyes musing). Not sure whether discussing it in more detail publicly is OK. 

We have backups but backups could be better, in terms of location, redundancy and longevity.

**Comment by GKFX** [comment]
One issue with putting a full DB dump on AWS is that we haven't got consent in the privacy policy to share personal data with third parties. This could probably be overcome by encrypting it though.

**Comment by CHTJonas** [comment]
Oh yes absolutely - sorry for not mentioning that earlier! In my opinion a backup that isn't encrypted is asking for trouble (and breaking GDPR as you say)...

Obviously this depends a lot on the backup methodology/software but I tend to encrypt a lot of my personal backups for my PGP key. Could do something similar here ie. pipe the output of `tar` or `mysqldump` through GPG? Filesystem backup software tends to either use PGP/GPG (eg. Duplicity) or its own implementation based on a symmetric key (eg. Restic).

**Comment by GKFX** [comment]
That sounds very reasonable. Although would possibly be worth compressing it first to save you a few quid.
Also I would suggest generating and using a Camdram key instead and distributing it to the rest of us at some point, so that if you spill tea on your laptop, we don’t lose all the backups 😉

**Comment by hoyes** [comment]
This all sounds great and no strong opinions here so feel free to go ahead with whatever strategy you think is best. 'Tis much needed.

For images, I'm wondering if we could get away with just storing them in a single versioned S3 bucket (https://docs.aws.amazon.com/AmazonS3/latest/dev/Versioning.html). If we switched to using incrementing IDs as the filename (which is probably a good idea anyway) it should mean we never overwrite anything anyway, but the versioning thing would give an extra level of protection against a random script accidentally doing something bad.

We currently have about 250 Mb of images, which I *think* would come to <$1 a year (if I've done my maths right) for a single snapshot. I'm happy to contribute a little something to S3 costs too for now, but yea should try and figure something out for #298.

**Comment by philosophicles** [comment]
> Method 1 is a lot more complex, but has the advantage that a retired admin cannot decrypt backups once they leave (current admins change the password for the 'Camdram Administrators' key and then reencrypt and redistribute).

I am absolutely not a crypto expert, but what is to stop an admin obtaining the actual 'Camdram Adminstrators' private key while they have access to the passphrase, then storing the actual private key somehow on their own so they can still use it after retiring from Camdram? 

This is extreme edge-case security thinking; I highly doubt that any Camdram admin would ever want to do anything Bad after they retire from Camdram. But I figured I'd ask as maybe I'll learn something from the answer ;-)

**Comment by CHTJonas** [comment]
Improved DB backups are now happening. This is a on/offsite arrangement with local copies deleted as they get old only if they have been mirror to the cloud (where they are stored permanently):

- The `db-backup` user's crontab runs `/db-backups/backup.sh` at regular intervals with the appropriate arguments;
- If successful, `/db-backups/housekeeping.sh` is then run which mirrors to AWS.
- If the mirror was successful, files that are appropriately old are locally deleted.

**Comment by CHTJonas** [comment]
> what is to stop an admin obtaining the actual 'Camdram Adminstrators' private key while they have access to the passphrase, then storing the actual private key somehow on their own so they can still use it after retiring from Camdram

Yeah so this is definitely a loophole, and one I can't immediately seem to resolve however I think about it 🤔. I originally read about this method somewhere online but now I can't seem to find it. In any case if an administrator takes a copy of a backup and copy of the private key + passphrase they can do whatever they like. Short of decrypting all past backups and then re-encrypting afterwards I can't see a way around this problem.

From the search I did find that GitLab encrypt their DB backups using a shared company-wide PGP key, the password for which is stored in their 1Password vault ([source](
https://gitlab.com/gitlab-com/runbooks/blob/master/howto/using-wale-gpg.md#production-1)). We could do something similar and have the password reside in a Camdram KeePassXC vault in a Google Team Drive? (I'm sure other free password vaults are out there but this is the one that I happen to use. Happy if someone want to propose something else that's free 😄)

@hoyes I was thinking of using [Restic](https://restic.net) to backup all the images. It's versioning and deduplicating, but would mean a separate symmetric key/password as it doesn't use PGP. Personally I use it for my VPS and really like it, but again if anyone has any suggestions here feel free to shout!

**Comment by CHTJonas** [comment]
Or, as you say, we do transition away from md5 image names and switch to numeric IDs and just mirror the folder without encryption (since all images are publicly available anyway).

**Comment by CHTJonas** [comment]
I should add that I have some AWS credentials and API keys to share with you all so maybe as password vault would be a good idea (apologies for triple posting...)

**Comment by GKFX** [comment]
Would probably be easier for you to encrypt them with our GPG keys and then just email them to webteam.

**Comment by CHTJonas** [comment]
Ideally some kind of database would be preferable as new keys will invariably need to be added/old keys rotated and this would make it so much easier than having to redistribute an encrypted text file to everyone.

**Comment by CHTJonas** [comment]
I've left the current system of DB backups running for a while and whilst I think it's working great, it's using in excess of 20,000 PUT/GET requests per month which is, quite frankly, ridiculous (and means we're being charged excessively).

I'm going to change the script so that we don't 'sync' the entire local repository, rather just upload the latest backup.

**Comment by CHTJonas** [comment]
I've just written a script at `/root/cron/fs-backup.sh` that handles filesystem backups. Currently it makes a TARball of everything under `/var/www/camdram/production/shared`, compresses it, encrypts it and uploads it to S3. This is called by the `root` crontab at half-past midnight everyday. We might want to revisit this in the near future and look at storage usage/projected costs.

**Comment by CHTJonas** [comment]
This has been working well for a while and I've tested doing a full restore on multiple occasions myself, as has @GKFX. Credentials for S3 are in the Keybase vault so closing now.
