### ISSUE TITLE
Can't delete any roles

### ISSUE THREAD

**Issue by tc467** [camdram/camdram#444]
The page for pirates of Penzance at the Minack 2018 is not being recognised when searched for. The page will also not allow me to reorder characters and prod team. It will also not delete roles.

**Comment by GKFX** [comment]
Hi Tiffany, if I impersonate your user account I do see all the usual buttons and I can reorder people. Could you post a screenshot of what you see? Also browser details etc.

For search I suspect that your search ranking is just lower than old performances of Pirates, so it doesn’t appear. We’re aware of this as an ongoing bug.

**Comment by GKFX** [comment]
I can see the show in search results for “minack” so I think that’s fine. It does turn out that I can’t delete roles using your account or mine – I’ll delete the test role I added when I get back to a PC and then look into this for you.

**Comment by tc467** [comment]
Hi.
So it reorders it for about 10 minutes or so and then goes back to how it was before.
If you type in Pirates of Penzance it doesn't show up at all unfortunately-and also it's not been showing up as counting towards people's camdram credits (for example it shows up on my camdram page but my credits say 23 instead of 24). And the thing we want deleting is the major-general role with Michael Morrison playing the part, if that's ok?

Thank you
Tiffany

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by hoyes** [comment]
Deleting roles should now be fixed on https://development.camdram.net.
