### ISSUE TITLE
Fix/depreciate extlogin flow

### ISSUE THREAD

**Issue by CHTJonas** [camdram/camdram#457]
The extlogin flow is currently not working. This is affecting a few third-party applications.

My vote would be to transition all applications using `/extlogin?redirect=url` for logins away from this to OAuth (or notify their respective owners). We can then fully remove all the code that handles this login flow and drop the `acts_externalsites` table.

**Comment by hoyes** [comment]
This is only used by ADC room booking and ticket sales these days, and yes I'd love to delete this as soon as possible. It's easy enough to fix for now though (it's using a service that no longer exists in Symfony 3 and fell under the radar when doing #424).

I have made the necessary mods to make Ticket sales use OAuth somewhere - can dig this out if it's fallen under the radar. I'll defer to @CHTJonas for room booking - depending on likely timeline could either wait until the new site is ready or could probably adapt just the login flow of the existing room booking site without too much effort.

**Comment by hoyes** [comment]
Fixed above. Kinda hard to test, but I've added the relevant externalsite to the dev DB and https://development.camdram.net/extlogin?redirect=http://roombooking.adctheatre.com/blah now renders.

Leaving ticket open in case as there's maybe still stuff to discuss on the direction to take with this.

**Comment by hoyes** [comment]
Looks to be working now on www.

**Comment by hoyes** [comment]
Dicussion re room booking and ticket sales happening elsewhere so closing this.
