### ISSUE TITLE
Server-side API authentication

### ISSUE THREAD

**Issue by hoyes** [camdram/camdram#460]
Loose end from #24 

Support performing a server-side API request without going through . I *think* the FOSOAuthServerBundle already supports grant_type=client_credentials, which would probably be sufficient for this. But either way, would need investigating, and probably tests + documentation adding too if we want to support it.

**Comment by CHTJonas** [comment]
Having a play with this and it seems to work!
```bash
curl --request POST \
--url 'https://www.camdram.net/oauth/v2/token' \
--header 'content-type: application/json' \
--data '{"grant_type":"client_credentials","client_id": "changeme","client_secret": "changeme"}'
```
Returns:
```json
{"access_token":"blah","expires_in":3600,"token_type":"bearer","scope":"user_email user_shows user_orgs api_write api_write_org"}
```

NB: I've been working on https://github.com/CHTJonas/camdram-ruby over the last few months as a kind of de-facto implementation of an API client (mostly for the new room booking system) so will integrate the above and let you know how my unit tests play out.

**Comment by CHTJonas** [comment]
I think I've found an issue, but it's possibly user error! An OAuth token that's returned to an API client through the Camdram login + redirect flow should be able to be refreshed using the returned refresh token. However this doesn't seem to work 😞 

```bash
curl --request POST \
--url 'https://www.camdram.net/oauth/v2/token' \
--header 'content-type: application/json' \
--data '{"grant_type":"refresh_token","refresh_token":"myrefreshtoken","client_id":"myclientid","client_secret":"myclientsecret"}'
```

Returns:

```json
{"error":"unauthorized_client","error_description":"The grant type is unauthorized for this client_id"}
```

**Comment by CHTJonas** [comment]
Suggest we split documentation & unit testing off into #423 and leave this ticket just for code enhancements/bugs.

**Comment by CHTJonas** [comment]
Have tested this a lot with New Room Booking recently and seems to be working fine, including refreshing access token. I've only tested the [client credentials](http://tools.ietf.org/html/draft-ietf-oauth-v2-15#section-4.4) and [authorisation code](http://tools.ietf.org/html/draft-ietf-oauth-v2-15#section-4.1) OAuth strategies but I think that's fine for now. If anyone in the future really wants to use a different strategy and we consider it secure enough then we can implement it then, but closing this ticket for now.
