### ISSUE TITLE
Split venues from societies in database

### ISSUE THREAD

**Issue by CHTJonas** [camdram/camdram#465]
Slight nag that I've just noticed but not affecting operation in any way so lowest priority. Currently `acts_societies` contains records for both registered societies and venues, differentiated by the `type` field. The venues should probably me migrated out into a separate `acts_venues` table.

**Comment by hoyes** [comment]
Totally agree - this is a hangover from v1 and had similar thoughts but didn't get around to creating the ticket...

A small complication is that the access control system currently uses the "Organisation" base class to group together a user's admin rights for societies as the same thing (i.e. /accounts/organisations.json), but if we split them into separate tables then it'll no longer be possible to do queries on all "organisations". See https://github.com/camdram/camdram/blob/master/src/Acts/CamdramSecurityBundle/Security/Acl/AclProvider.php and callees.

Tempted to say we go the full way and:
 * Remove the Organisation base class (+OrganisationRepository, OrganisationController etc)
 * Make the access control system use separate "society" and "venue" keys for admin rights
 * Change to use separate /accounts/societies.json and /accounts/venues.json, before anyone starts using it in earnest (room booking etc...). Or could maybe just change to /accounts/aces.json which returns all admin, show, venue and society access rights in one place.

**Comment by CHTJonas** [comment]
Yeah I was just looking at the code and came to the same conclusion. The whole Organisation model would need refactoring and relevant bits bringing into Society and Venue.

In my mind `/accounts/societies.json`, `/accounts/venues.json` and `/accounts/shows.json` seems more logical. Personally I think it's slightly nicer for third parties to split them at the API level rather than letting them parse the response from `aces.json` themselves but either is fine really.

**Comment by hoyes** [comment]
Cool. There might be ways of improving the acts_access schema too at some point which would be easier if we don't expose that table in the API.

**Comment by GKFX** [comment]
Btw this is very much related to #191. While I’m not actually trying to fix this for #191, it would be helpful not to start working on this bug until I’ve merged in my changes, as otherwise there’d be severe conflicts between what I’ve done and what anyone else might do.

**Comment by GKFX** [comment]
For venues: it currently makes no sense that both shows and performances have an associated venue. For tour shows, the show venue has to contradict some of the performance venues. I would suggest dropping the show.venue/show.venid columns at the same time as this since the access control stuff is going to need a re-write anyway.

**Comment by philosophicles** [comment]
_Expresses hearty noises of celebration that this v1 data model beast has been slain_
