### ISSUE TITLE
Google Maps has stopped working

### ISSUE THREAD

**Issue by hoyes** [camdram/camdram#469]
https://www.camdram.net/venues has started erroring because "You have exceeded your request quota for this API." Google's messaging on the subject is a little cryptic, but (from https://cloud.google.com/maps-platform/user-guide/pricing-changes/):

> Can I still use Google Maps Platform for free?
    Yes. When you enable billing, you get $200 free usage every month for Maps, Routes, or Places. Based on the millions of users using our APIs today, most of them can continue to use Google Maps Platform for free with this credit.

The Google API console now says our limit is "1 access per day", which can be raised by "enabling billing" which seems to concur.

Suggest we switch to something based on OpenStreetMaps - looks like https://leafletjs.com/ and http://openlayers.org/ are the most widely used.

**Comment by CHTJonas** [comment]
I was reading a discussion on this very issue on another open-source project and there was talk there of the difficulty switching to OpenStreetMaps because, apparently, it involves hosting or negotiating access to a ‘tile server’ to render from the vector map data. I’m not sure exactly what was being talked about but thought I’d bring it up just in case it’s relevant to us. I can probably link to the discussion if needed (sorry on mobile at the moment).

**Comment by GKFX** [comment]
Would be worth looking at https://map.cam.ac.uk. It’s displaying a lot of good information like bike parking and college details, and any OpenStreetMap embedding we do should probably aim to display similar information.

**Comment by hoyes** [comment]
Hmm... maps.cam.ac.uk even has its own JS API and tile server... https://wiki.cam.ac.uk/university-map/The_Tile_API and I think the terms of use (https://wiki.cam.ac.uk/university-map/Terms_and_conditions,_Copyright,_Fair_Use,_etc.) are suitable

**Comment by mvl22** [comment]
I see that some great work has been done on this already. In case the following is useful, here is my usual introduction to open web mapping advice (being a University staff webmaster with a mapping expertise specialism):

> Suggest we switch to something based on OpenStreetMaps

Strongly recommended. 

> looks like https://leafletjs.com/ and http://openlayers.org/ are the most widely used.

Leaflet.js is far more heavily-used these days and is more developer-friendly.

My introductory guide to web mapping may be useful for those without knowledge of this area:
https://github.com/mvl22/openwebmapping
In summary, you just create the data as a file/API call in GeoJSON format (which then makes it trivially repurposable data), and then load that into Leaflet using an AJAX call. You can then style the icons, etc. if wanted.

The other key thing, as noted above, is having access to background tiles. These are run using a 'tileserver', which is the thing that serves the bitmap images forming the background. Leaflet.js automatically arranges each 256x256px tile on the canvas so it appears to be a single uniform map.

- There should be no problem using the [map.cam.ac.uk tiles](https://map.cam.ac.uk/#52.204678,0.118774,17) - they encourage usage for University purposes.
- The [OpenStreetMap (OSM) standard map layer](https://www.openstreetmap.org/#map=16/52.2012/0.1177) is quite nice and practical. The OSM tileserver is predominantly for serving their own website, but their [usage policy](https://operations.osmfoundation.org/policies/tiles/) do allow some external usage, as long as usage isn't heavy. I think Camdram would be fine.
- [OpenCycleMap](https://www.openstreetmap.org/#map=16/52.2012/0.1204&layers=C), is a cycling/walking-orientated cartographic rendering of the same data from OpenStreetMap. It's quite a 'busy' layer, but is probably most useful. If you add a bit of opacity, it is perfectly usable as an overlay. An API key is required, which is simple to obtain; [usage is free under 150,000 tiles per month](https://www.thunderforest.com/pricing/), which I'd have thought would be fine.
- A commercial provider of maps is [Mapbox](https://www.mapbox.com/), though they are moving more towards Vector Mapping, which is more complex to implement and unnecessary for a simple display of venues.

Basically I would recommend signing up for OpenCycleMap, and using their tiles in a Leaflet-based map, and making a GeoJSON API serving the venues.

**Comment by hoyes** [comment]
Cheers @mvl22. I'd say I'm leaning towards using OSM being slightly less noisy than OCM at the default zoom used on Camdram. Didn't realise external usage was allowed so that's good to know.

There's a WIP in maps-react which I hope to finish off in the not too distant future. May end up taking React out as it's the only place using it atm.

I'm on the fence about GeoJSON - https://www.camdram.net/venues.json already provides the coords in a similar way to the rest of Camdram with little code overhead. Camdram's traditionally been somewhat conservative on the feature front for reasons of longer term maintenance but I imagine this is something we'd accept a pull request for.

**Comment by mvl22** [comment]
The benefit of GeoJSON is that you can then load it directly using [L.geoJSON](https://leafletjs.com/reference-1.3.4.html#geojson) and it just knows what the data structure is. With flat JSON you have to write the lookup of data structure -> map manually. The purpose of GeoJSON is to take data that is geographical and just throw it straight onto the map with barely any work, because it provides a standard layout.

Obviously you do then have to write a GeoJSON renderer for the data sid though :)

Or, as you already have flat JSON, there is a useful little library, [GeoJSON.js](https://github.com/caseycesari/geojson.js/#example-usage) which dynamically converts flat JSON to GeoJSON.

**Comment by hoyes** [comment]
Fixed by PR #522 (preview at https://master.dev.camdram.net/venues)
