### ISSUE TITLE
Social media icon regression on show pages

### ISSUE THREAD

**Issue by CHTJonas** [camdram/camdram#471]
The Facebook icon appears to be in some kind of grey scale.

![ded61b66-d942-4ab0-a690-ff29ea35472b](https://user-images.githubusercontent.com/17813061/43712700-576bf11e-9977-11e8-82c8-36e8e87f799b.png)

I’m viewing this on mobile at the moment.

**Comment by GKFX** [comment]
It needs a class added, I’ve been meaning to get round to this. I can sort it after work.
