### ISSUE TITLE
Sentry logging integration

### ISSUE THREAD

**Issue by hoyes** [camdram/camdram#474]
An idea suggested internally was to integrate https://sentry.io/ to get better exposure of errors that are occurring.

They have a Symfony bundle (https://github.com/getsentry/sentry-symfony) which requires a little work to integrate.

**Comment by hoyes** [comment]
@CHTJonas I signed up with the 'camdram' name to play around but haven't done anything else. Should have added you to the group.

**Comment by CHTJonas** [comment]
Currently we're on a free trial so we might want to think about doing a release soon and then reevaluate when the trial expires and we downgrade to the free plan.

**Comment by CHTJonas** [comment]
It works! Nice integration with GitHub too 😃
