### ISSUE TITLE
Multibyte characters are truncated incorrectly

### ISSUE THREAD

**Issue by GKFX** [camdram/camdram#475]
See e.g. https://www.camdram.net/people/christopher-mcnamara:

> “Theatre should be grand, vulgar, simple, pathetic – not genteel, not poetical.” So said Joan Littlewood, artistic director of the infamous Theatre Workshop and developer of the seminal …

where a curly single quote appears to have been cut in half, resulting in an unknown character in the end.

**Comment by GKFX** [comment]
Very interesting, I would have thought this would be platform-independent. Can’t reproduce on iOS Safari either, but I have seem this multiple times on Linux. Perhaps there are platform differences in how malformed UTF8 is rendered or something. Either way it should be possible to check what exact bytes we are serving there and ensure it is valid.

**Comment by CHTJonas** [comment]
Running `curl https://www.camdram.net/people/christopher-mcnamara` in a terminal gives me something like this if it helps:
```
<p>“Theatre should be grand, vulgar, simple, pathetic – not genteel, not poetical.”

So said Joan Littlewood, artistic director of the infamous Theatre Workshop and developer of the seminal &#03&hellip;</p>
```

**Comment by GKFX** [comment]
I can't see anything in Firefox on Linux either. However the HTML validator [doesn't like it](https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.camdram.net%2Fpeople%2Fchristopher-mcnamara) – I believe I've already fixed all the errors not linked to this ticket btw. That HTML is very odd, I'm bemused as to what sort of encoding issue (or anything else) could result in a truncated entity for a control character!

You can apparently add a second parameter (`true`) to the truncate filter to preserve whole words: https://twig-extensions.readthedocs.io/en/latest/text.html. This would presumably be a good work-around in that it would force it to break at characters it can comprehend. I can't test this theory in the next week but will have a shot at it then, unless someone else beats me to it.

**Comment by GKFX** [comment]
Worth pointing out that my above comment was 100% wrong; we actually have our own TextService, rather than using the official one, and it was using the wrong PHP substring function.
