### ISSUE TITLE
Firefox Tracking Protection blocks Twitter images and googletagmanager

### ISSUE THREAD

**Issue by GKFX** [camdram/camdram#478]
Result is a load of missing images which doesn't look great. I guess we should just save the images onto Tiberius? Potentially in a dedicated /twitter/ directory somewhere appropriate.

I'm not quite sure that fixing/replacing Google Tag Manager is a priority. I assume it's only linked to analytics? I guess there'll be some way of doing that server-side and keeping Google out of it but we arguably have bigger issues than keeping track of e.g. what time of day our Firefox users use Camdram.

**Comment by GKFX** [comment]
In terms of non-Google analytics I was imagining something on Tiberius which analyses e.g. server logs and gives us e.g. usage levels by hour and page popularity info, nothing privacy-invading, and certainly an improvement on sending everything to Google. But as above this should probably be considered pretty low priority, as somehow I don’t think Chrome is going to start blocking Google Analytics any time soon. (They might try to charge us for it though!)

And yes, if we’ve already got something suitable installed for images that’s great!

**Comment by hoyes** [comment]
https://goaccess.io maybe ?

**Comment by hoyes** [comment]
https://logs.camdram.net/ boom!

**Comment by hoyes** [comment]
Closing as Twitter images are now proxied and admins have agreed that GA along is sufficient for now
