### ISSUE TITLE
/people needs some content

### ISSUE THREAD

**Issue by CHTJonas** [camdram/camdram#487]
The page at https://www.camdram.net/people is currently 500'ing. We should probably change this so some static content is rendered instead, or a random selection of people recently added, or maybe a list of people involved in shows that week?

https://sentry.io/camdram/camdram/issues/647437811/

```
BadMethodCallException: Undefined method 'selectAll'. The method name must start with either findBy or findOneBy!
  File "src/Acts/CamdramBundle/Controller/AbstractRestController.php", line 265, in cgetAction
    $qb = $repo->selectAll()->getQuery();
  File "web/app.php", line 28
    $response = $kernel->handle($request);
...
(7 additional frame(s) were not displayed)
```

**Comment by GKFX** [comment]
People in shows this week sounds good, perhaps with a re-phrased version of the homepage stats bar?

Just listing all new people is a bit arbitrary, it depends on e.g. the order that people are added by producers. That said it would be nice to list new people prominently; maybe order the people in ascending order of number of credits?

Also if a person-specific search bar is easy to make that would also fit quite well.
