### ISSUE TITLE
Main site Contact Us webform is broken

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#488]
Submitting the form at https://www.camdram.net/contact-us triggers our vague "Something's gone wrong" Error 500 error page. 

This happens with a real/normal name and email address provided (mine), and brief, simple Subject and message body (no wacky characters etc). 

See Sentry issue [CAMDRAM-D](https://sentry.io/camdram/camdram/issues/651911148/). The submission of this form appears to be calling a non-existent `acts.camdram.email_dispatcher` from 
CamdramBundle/Controller/ContactUsController.php.

**Comment by hoyes** [comment]
Postal is blocking the contact form

**Comment by hoyes** [comment]
Works fine if the "From" field is a camdram.net address. Either need to figure out a way to trick Postal into accepting the e-mail in such a way that the From: address arrives correctly in Brimir (maybe by setting Reply-To instead), or perhaps just POST directly to Brimir from the contact form.

**Comment by hoyes** [comment]
Now working.

**Comment by CHTJonas** [comment]
Is this the same bug as that in Sentry issue [CAMDRAM-C](https://sentry.io/camdram/camdram/issues/648606826/)? Have already marked the one listed above as resolved but wasn't sure about this one although it seems similar.

**Comment by hoyes** [comment]
Looks different. Wonder if it's somehow to do with the really long slug.
