### ISSUE TITLE
HTTP 500 error on deleting a user from their page

### ISSUE THREAD

**Issue by GKFX** [camdram/camdram#498]

**Comment by CHTJonas** [comment]
I wonder if this is the same issue as #425? I presumed in that case it was because the user was merged, but maybe it’s all related to the same logic bug?

**Comment by CHTJonas** [comment]
Going to assume that this is the same issue as this [Sentry issue](https://sentry.io/camdram-webteam/camdram-web/issues/763798324). Looks like we are not currently dropping a user's rows in `acts_access` when we delete said user.
