### ISSUE TITLE
Search button/bar not working consistently on Chrome for Android

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#499]
Android 7.0.0
Mobile site on Chrome app 68.0.3440.91

I tap on the magnifying glass icon to search; the search bar starts sliding open leftwards from the icon, but retracts again almost immediately, never getting further left than about the 'R' or 'A' of the main CAMDRAM logo. (It gets a variable distance before retracting, sometimes never even touching the 'M'.)

This happens approx 2/3 of the time I tap it. If I tap it repeatedly, eventually it will open all the way and allow me to search. 

Tagging as a regression as I presume (but can't remember explicitly) that this worked at some point in the past!

**Comment by GKFX** [comment]
Damn. The hidden search bar is new, I added it in the last release. Unfortunately I don’t have an Android 7-capable phone and can’t reproduce on iOS Safari or Chrome. I’ll see if I can get my ancient Android to reproduce it.

**Comment by GKFX** [comment]
@philosophicles I've fixed it for my phone, but seeing as I'm on Android 4.1.2 that's possibly a bit irrelevant! I've pushed the fix to development.camdram.net; could you let me know if this is working for you and if it is I'll do another release. Thanks for spotting it!

**Comment by philosophicles** [comment]
Yep, that's working consistently for me now. Good job - it is a really nice UI feature on a small screen!
