### ISSUE TITLE
HTML encoding issue in sign-in sheet

### ISSUE THREAD

**Issue by GKFX** [camdram/camdram#508]
![30583114-ece0-4571-abef-e7dbf39429ae](https://user-images.githubusercontent.com/5357642/47032293-ef380f80-d169-11e8-8d0a-c3bacb81c3fa.jpeg)

**Comment by CHTJonas** [comment]
Looks like an issue with single quotes/apostrophes when printing out CSV sign-in sheets for any show (the `text/html` version is not affected). Eg.
- https://www.camdram.net/shows/2018-the-childrens-hour/signinsheet.csv
- https://www.camdram.net/shows/2018-im-having-a-wonderful-time-in-baden-baden/signinsheet.csv
- https://www.camdram.net/shows/2018-musical-theatre-bar-night-freshers-set/signinsheet.csv

**Comment by GKFX** [comment]
So my guess is that as we have Twig set to automatically sanitize variables it’s doing that for everything including CSV. Solution is probably to define a csvEncode Twig function and then pipe all variables in CSV templates like `{{ blah | csvEscape | raw}}`.

**Comment by hoyes** [comment]
Could maybe adapt to use https://symfony.com/blog/new-in-symfony-3-2-csv-and-yaml-encoders-for-serializer

**Comment by GKFX** [comment]
I couldn't quite figure out how to use CsvEncoder successfully, but it turned out to just use `fputcsv` internally, which is very easy to use.
