### ISSUE TITLE
Layout issues

### ISSUE THREAD

**Issue by CHTJonas** [camdram/camdram#509]
Few little things I noticed after the deploy of 2.54. Not sure if they were issues before or regressions:
- Show credits text size seems to have got a lot smaller.
- When you have multiple people listed under the same role, there is an unnecessary space before the comma (ie. `Co-Producer - Alix Marie d'Avigneau , Lucy Roberts`).

**Comment by GKFX** [comment]
The credits text size looks reasonable to me on Linux/Chrome, Linux/FF, and iOS Safari. What platform are you seeing an issue on? The computed font size is 14px on both of the Linux browsers if that helps with comparison.
I've found the extra whitespace behind the comma issue.

**Comment by CHTJonas** [comment]
Am viewing on Safari/macOS and also computed `font-size: 14px` in the web inspector. Is it just me that thinks it's got smaller since the previous (v2.53) release?! Maybe I'm crazy and it's always been like that! 🤣

**Comment by GKFX** [comment]
I've checked on web.archive.org and the original size was 16px, but looking at that now seems too big! The other big difference is that the line-height has got taller, so everything looks a bit more spaced out. Perhaps that makes the text seem less dominant?

**Comment by CHTJonas** [comment]
Perhaps! It seems largely fine so let's leave this closed unless anyone complains or there's significant desire to change it to be similar to before.
