### ISSUE TITLE
JPEG compression used for Footlights logo thumbnail when PNG would be more appropriate.

### ISSUE THREAD

**Issue by GKFX** [camdram/camdram#510]
The JPEG artefacts are quite significant; as most logos are non-photographic we should be serving only PNGs.
![image](https://user-images.githubusercontent.com/5357642/47150101-7356d800-d2cd-11e8-9edd-56b0bec07e30.png)

**Comment by hoyes** [comment]
It looks like we preserve whatever the original file format is so arguably this is a user error.

https://github.com/camdram/camdram/blob/master/src/Acts/CamdramBundle/EventListener/ImageListener.php is the current logic. It looks like we blindly pass through anything that PHP GD can handle (http://php.net/manual/en/intro.image.php) - maybe we should limit to certain file formats?

Not sure what would happen if the client hands us a seemingly valid MIME type but the data itself is malformed - there are probably some exceptions we're not handling which would result in a 500 error.
