### ISSUE TITLE
Expanded search matching

### ISSUE THREAD

**Issue by CHTJonas** [camdram/camdram#519]
Searching for `'footlights tour'` returns only a handful of entries whereas `'footlights international tour'` returns something more like I was expecting. Are there any performance penalties to changing search matching so that words don't necessarily have to be included in-order?

Eg. someone lazily searches for `'fashion show charity'` then results for Cambridge University Charity Fashion Show are returned. Vaguely related in some ways to #341.

**Comment by GKFX** [comment]
Done
