### ISSUE TITLE
Deleting a show fails when its slug has been changed

### ISSUE THREAD

**Issue by CHTJonas** [camdram/camdram#526]
Deleting a show where the show slug has been changed throws a 500 error because of the foreign key constraint of `acts_show_slugs.sid` on `acts_shows.id`. Just need to purge the slugs table first before removing the show.

Sentry Issue [CAMDRAM-WEB-74](https://sentry.io/camdram-webteam/camdram-web/issues/776167042)

**Comment by philosophicles** [comment]
Shows that should be deleted once this has been released: 
* https://www.camdram.net/shows/2019-the-wolves
* https://www.camdram.net/shows/2018-signet-short-film

**Comment by hoyes** [comment]
:arrow_up: deleted
