### ISSUE TITLE
Fix CSRF vulnerabilities

### ISSUE THREAD

**Issue by CHTJonas** [camdram/camdram#533]
Currently a GET request to the show deletion URL will result in the show being deleted without the user being prompted (tested with https://master.dev.camdram.net/shows/2018-test/remove). The same appears to be true for venues and societies, leaving us **very** vulnerable to a [cross-site request forgery attack](https://www.incapsula.com/web-application-security/csrf-cross-site-request-forgery.html) against admin accounts.

In an ideal world the correct restful action would be a DELETE request to the `/shows/slug` endpoint however it might be safer (more compatible) to use a POST request to `/shows/slug/remove`. [Seems like](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE#Browser_compatibility) most browsers support the DELETE method though.

**Comment by hoyes** [comment]
Good spot. I can think of at least one other privileged action that is performed via non-validated GET requests too and is available to non-admins.

**Comment by GKFX** [comment]
https://github.com/camdram/camdram/commit/c0e9b77d4e065c0e1b0ac46c979f8559f7fa8b34 implements the UI for (nearly) this, specifically in app/Resources/views/navigation/form-item.html.twig.

**Comment by hoyes** [comment]
Some thoughts:
 * Symfony has a built-in mechanism for overriding the method using a hidden form field, which could maybe be employed here (https://symfony.com/doc/3.4/form/action_method.html - see final note).
 * Forms generated by Symfony do CSRF protection automatically (https://symfony.com/doc/3.4/form/csrf_protection.html).
 * Alternatively, can trigger the Symfony CSRF mechanism manually using https://symfony.com/doc/current/reference/twig_reference.html#csrf-token and https://symfony.com/doc/3.4/controller/csrf_token_validation.html

The output of https://master.dev.camdram.net/shows/war-horse/edit makes use of both the above (albeit that it's a bit obfuscated via magic functions in the Twig template).

**Comment by CHTJonas** [comment]
To be honest I think that triggering the manual CSRF mechanisms is a bit overkill. From the perspective of a third-party application using the API adding that step would (I think?) require the app to first make a request to get the CSRF token before making the requests which actually deletes the resource...? That being said if we're implementing token for all forms automatically then you could argue we should do it here as apps will be expecting it. (I might have got this wrong - not sure if using an OAuth token bypasses CSRF as it's assumed to be privileged)

My vote would be to just use the built-in `_method` field - no point reinventing the wheel. I'm assuming that under these circumstances the Symfony router would recognise both a genuine DELETE or a fake `_method=DELETE` POST request to the same endpoint, that way API apps are restful and the website is CSRF-protected.

**Comment by hoyes** [comment]
:point_up: Changed to use DELETE for all delete actions and I've changed a bunch of other places to use PATCH too. All with CSRF tokens.

I've almost certainly missed something... reopen if anyone spots something.
