### ISSUE TITLE
Don't send venue/society/show admins an email when changes are made by a site admin

### ISSUE THREAD

**Issue by CHTJonas** [camdram/camdram#546]
Some kind of feature to hold and/or drop outgoing email messages when bulk update actions are being performed. Maybe just ignore outgoing emails if an admin made the change?

**Comment by hoyes** [comment]
Swiftmailer has a catch-all `disable_delivery` that could be trivially exposed as a parameter or env var. It's set in config_test.yml for obvious reasons but otherwise unexposed.

**Comment by CHTJonas** [comment]
Ah okay that's where it was - spent ages in the Postal UI looking for that! My thoughts were to expose something in the web UI to administrators as a quick/dirty way to disable email delivery without console access eg. from a phone. Would this be overkill maybe?

**Comment by hoyes** [comment]
It doesn't look like it's possible to disable email delivery globally from PHP at runtime, so we could only do it by building a layer on top which feels a little overkill. The Postal UI is just about usable from a phone...?

I think we can "fix" this by default by taking admins into account in the outcome of #538 (i.e. if we opt to restrict changing societies to admins only then we may as well delete those emails altogether), and fix #547. (just created) The only time an admin could then generate spam is by explicitly adding admins to shows/societies/venues, which I _think_ is less problematic.

Also created #548 which is somewhat related.

**Comment by GKFX** [comment]
An alternative interpretation of the problem is
* Find a good solution to #548 so that mass changes don't lead to mass emails
* Have the ability to specify edit summaries and implement #198.

Arguably show/soc/venue admins should have visibility on changes made by a site admin, but need some explanation of what's happened and why rather than just receiving 30 emails all lacking proper context.

**Comment by CHTJonas** [comment]
I agree with @GKFX here I think so propose we close this in favor of #548.
