### ISSUE TITLE
Remove legacy API

### ISSUE THREAD

**Issue by CHTJonas** [camdram/camdram#550]
Briefly resurecting some of the discussion points from #78 as it's popped up again recently.

The legacy API is still a seemingly crucial part of the ADC's infrastructure as evidenced by some recent discussions & emails from management. Their last web redesign (circa 2016/17 I think?) did improved compatibility with Camdram, although I have no idea if they're using the new API for that. I am also led to believe that they themselves now have a copy of the source code which is hosted & running on-site.

I recognise that it's important we work with the ADC, but ultimately as @philosophicles outlines in #78, we cannot let development be affected by hangovers from v1 to too great an extent. After four-and-a-half years I do believe that it's time for this API to be retired. My understanding is that the only applications still 100% reliant on this are Room Booking (soon to be replaced anyway) and Ticket Sales. I propose that we decide on a date sometime in early- or mid-2019 when the API be removed from Camdram.

My argument for this is that it uses outdated authentication, is a maintenence burden and is just unnecessary given we have a (reasonably) stable v2 API. Without wanting to sound harsh I think 4 years is plenty time enough and in giving several months notice to the Theatre, we are within our rights to retire this. I also think that it would be in their best interests given that it has broken several times in the last year. Additionally, the current systems which this legacy API supports suffer from additional problems (eg. current room booking only runs on PHP5 and therefore has to run on Debian Wheezy which has ceased security updates) so it not unreasonable to expect some development work be needed on these old applications anyway; modernising their usage of Camdram's APIs could easily be included at the same time.

**Comment by GKFX** [comment]
I've asked Nat (current TM) to comment so we know what's actually in use.

**Comment by CHTJonas** [comment]
Thanks @GKFX! I'm aware my initial comment above may seem a bit 'harsh' from the theatre's perspective - after all they drive us traffic and in exchange we make management of their systems slightly easier by presenting them show/people data. And technically it is us that keeps breaking it by adding new features etc. 😛 It's meant with no offence intended at all; ideally Camdram & the Theatre can work together over the next few week/months - there's no particular rush.

Personally I just see limited mileage in a repetitious cycle of patching the stuff that's in `CamdramLegacyBundle` to work with new features. I think it would be better for both sides to transition to [newer systems](https://github.com/CHTJonas/roombooking) which integrate & authenticate much more nicely (and much more securely too).

**Comment by hoyes** [comment]
A bit of context:

#78 refers to another legacy API that was used by the ADC website to obtain role data for their show pages prior to the redesign that happened in circa 2015. I deleted it in https://github.com/camdram/camdram/commit/c5535f5d1b3c8c036773e4447ad6f234782d98ac#diff-b6c22b958e0c39b4f5bcb426568a7bb0 as it was no longer used.

The ADC website today uses /shows/000-xxx/people.json. (https://github.com/camdram/camdram/blob/master/src/Acts/CamdramBundle/Controller/ShowController.php#L278) for more minor legacy reasons. Ideally it should use use /shows/000-xxx/roles.json IMO but that's not so big a deal.

The remaining "legacy" APIs are:
 * The "extlogin" flow, which is all that remains of CamdramLegacyBundle.
 * The out-of-repo "camdram_server.php" script that runs on a separate subdomain on Antigone.

Both the above are only in use by the ADC Theatre Ticket Sales and Room Booking sites AFAIK and it would make me very happy too to remove them both as soon as possible. As I see it, Camdram cares about both evolving the feature set, to make it increasingly more useful for the people that use it, and working with the the ADC to provide useful data, but ultimately the former takes precedent over the latter and I have been quietly muttering about this for a few years in various e-mail chains ;)

It sounds as though room booking is really close to being replaceable. I don't know the latest about Ticket Sales, but I shared a couple of patches with the relevant people a while back to make it use the supported OAuth/REST APIs which should be relatively straightforward to deploy. Either way, I feel like we're really close to making this happen if just a few more stars align...

**Comment by GKFX** [comment]
I’ve got an email from Paul Gotch; he thinks upgrading ticketsales to the new API should be relatively straightforward. It apparently needs to move to a new version of PHP anyway.

**Comment by CHTJonas** [comment]
This is done, bar removal of the out-of-repo `camdram_server.php` code.
