### ISSUE TITLE
Create a Camdram "user policy"

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#556]
Placeholder issue. We are considering / drafting a User Policy to be added to the site. This is being drafted offline for now by the site webteam, but will generate commits etc at some point.

**Comment by philosophicles** [comment]
When this is done, we should also re-review the existing [Privacy Policy](https://www.camdram.net/privacy). 

* Consider piggybacking off some of the precise definitions "we", "you", "Camdram" etc from the User Policy, to make the Privacy Policy a bit more rigorous. 
* Check for any duplication - I'm thinking mainly of the "When you create an account on camdram.net..." bullet in the Privacy Policy, which maybe could be removed in favour of similar text in User Policy. (Not sure: let's decide once User Policy is concrete.)

**Comment by philosophicles** [comment]
Thought for a little later: maybe it'd be wise to issue some kind of reminder of this user policy (or, a condensed set of highlights) to users when they become admin for a society or venue. Probably within the notification email I think (?) they already receive in that situation. Essentially like the message *nix users get when sudoing for the first time - remind them of the additional responsibilities of authorizing shows etc.

**Comment by philosophicles** [comment]
We probably also want to do a mailshot to all users when this goes live (changes to Privacy Policy for clarity (no change in actual behavior) and hey look, a new User Guidelines you should read).

**Comment by philosophicles** [comment]
I've realized this has a degree of overlap with #171. I'm potentially ticking off a few aspects raised in #171 with what I'm doing here.

**Comment by CHTJonas** [comment]
Yeah to be honest I really dropped the ball on #171. My WIP branch is probably very out of date but could probably be resurrected. I think that I did add a "I have consent of the individuals whom I am adding" checkbox to show pages that the user had to consciously tick in order to submit roles. That might be useful possibly?

**Comment by philosophicles** [comment]
No worries! You've made a bazillion other commits in the intervening time :) 

A tickbox as you describe would definitely still be useful - I haven't added anything at the point of actually adding roles, only the point of creating a show. 

I'm definitely not implying that #171 is completed by #594 - it isn't. I just bundled in some low-hanging fruit from there as part of this PR.

**Comment by CHTJonas** [comment]
To be honest I like the look of @GKFX's new warning panel in c08f876 and it's definitely aesthetically nicer than my checkbox ever was so let's just stick with that instead. At least until role editing is sorted as you suggest in Gitter, George.

**Comment by philosophicles** [comment]
Still to do: I am drafting an email that could be sent out to all users (and maybe to Gossip List also) informing them of the changed Privacy Policy and new User Guidelines. I will share with site admins for review before sending!

**Comment by philosophicles** [comment]
Email got sent (with just a little unexpected drama...) so this is now done!
