### ISSUE TITLE
Viewing a person is broken

### ISSUE THREAD

**Issue by CHTJonas** [camdram/camdram#561]
HTTP 500 when viewing any person eg. https://www.camdram.net/people/charlie-jonas

```
Unable to generate a URL for the named route "remove_person" as such route does not exist.
app/Resources/views/person/show.html.twig in displayBlock at line 13
```

Sentry issue: [CAMDRAM-WEB-85](https://sentry.io/camdram-webteam/camdram-web/issues/813689195)

**Comment by hoyes** [comment]
Only affects admins I think
