### ISSUE TITLE
Vacancy times one hour too late.

### ISSUE THREAD

**Issue by CHTJonas** [camdram/camdram#563]
Vacancy expiry times shown in the frontend are mis-aligned by one hour. Likely introduced by #543 which we thought would only be an issue during BST and so could patch before April - turns out it's an issue right now too 😢 .

Example:
https://www.camdram.net/shows/2019-legally-blonde/techie-advert/edit shows vacancy expires at 16:00.
https://www.camdram.net/vacancies/techies shows the same vacancy expires at 17:00.

Interestingly the API https://www.camdram.net/vacancies/techies.json shows the correct expiry time.

Support ticket: https://support.camdram.net/tickets/1304

**Comment by hoyes** [comment]
This is quite a cool bug:
 * The deadline time for techie adverts (and applications) is stored in a separate field to the date.
 * PHP doesn't have a time-only data type, so it gets deserialized as a `DateTime` object with the date fields set to the Unix epoch (1st Jan 1970)
 * Changes in #543 now mean that `{{ deadlineTime | date("H:i") }}` implicitly causes the "time" to be converted to the "Europe/London" timezone
 * It just so happens that from 1968 to 1971 the UK experimented with sticking in UTC+1 all year around (https://en.wikipedia.org/wiki/British_Summer_Time), so times on the 1st January 1970 get converted to "BST"...

**Comment by GKFX** [comment]
Wow. I guess you learn something every day!

**Comment by philosophicles** [comment]
https://xkcd.com/1883/ ;-)
