### ISSUE TITLE
Some links in emails are relative and therefore don’t work

### ISSUE THREAD

**Issue by GKFX** [camdram/camdram#565]
Apparently there’s a [`absolute_url()`](https://symfony.com/blog/new-in-symfony-2-7-the-new-asset-component#template-function-changes) Twig function (or there was in Symfony 2.7) – just need to see if that works.

**Comment by hoyes** [comment]
Do you have an example of this? All the URLs in app/Resources/views/email seem to be using [url()](https://symfony.com/doc/current/reference/twig_reference.html#url)

**Comment by GKFX** [comment]
(Also the links should all be HTTPS not HTTP.)

**Comment by CHTJonas** [comment]
How weird... Could perhaps try `diff`ing the emails by source in one client vs. another? Shouldn't be any different and I doubt they will but sounds like there's some monkey business going on here somewhere 🙈
