### ISSUE TITLE
Audition times off by 1 hour

### ISSUE THREAD

**Issue by CHTJonas** [camdram/camdram#568]
When submitting an audition, the value for the end time field is reduced by one hour. Submitting an audition with an end time of 17:00 results in the time being recorded as 16:00. Similar results for other times.

Support Ticket: https://support.camdram.net/tickets/1323

**Comment by hoyes** [comment]
I'll tackle this tonight and do a patch release

**Comment by CHTJonas** [comment]
Maybe related to this is [CAMDRAM-WEB-8A](https://sentry.io/camdram-webteam/camdram-web/issues/839779547). Looks like the `start_at` fields are both set to a string value of `Array of length 2`!
