### ISSUE TITLE
Contact form exception if entity doesn't exist

### ISSUE THREAD

**Issue by CHTJonas** [camdram/camdram#584]
Trying to contact a show, society or venue that doesn't exist will raise an `InvalidArgumentException` and thus 500. This is probably an issue only seen when shows change their title (and hence slug) whilst someone has the contact form loaded in their browser.

Eg. https://www.camdram.net/contact/show/2019-louisa-keight-jinkies versus https://www.camdram.net/contact/show/2019-louisa-keight-jinkies-w-i-p

Sentry issue: [CAMDRAM-WEB-6P](https://sentry.io/camdram-webteam/camdram-web/issues/765760008/?referrer=github_plugin)

**Comment by GKFX** [comment]
Fixed in 601fc778de8123a0c6af087538711d14b6ecec38.
