### ISSUE TITLE
Sign in sheets are omitting some performances

### ISSUE THREAD

**Issue by CHTJonas** [camdram/camdram#592]
The HTML and CSV sign in sheet generators appear to be omitting any performances which occur on a Saturday eg. https://www.camdram.net/shows/2019-legally-blonde/signinsheet. Reported to me by Jacob Baldwin and posted on his behalf as he doesn't have a GitHub account 😛 

Additionally, the CSV sheets when viewed in Microsoft Excel (which is probably the first application most people will turn to when wanting to edit/print them) contain a string of random garbage in the header eg. `Sign-in sheet for The Children's Hour (16/10/2018â€“19/10/2018 â€“ generated by Camdram` that isn't present in the original eg. `curl https://www.camdram.net/shows/2018-the-childrens-hour/signinsheet.csv`. From what I can tell using the Excel import CSV dialogue (as opposed to simply opening the file with Excel directly from Windows Explorer) it's because the character encoding is detected as Windows-1252 and not UTF-8.

**Comment by GKFX** [comment]
Re encodings: my view is that we should be using UTF-8 and Excel is just wrong! However that doesn’t really solve the problem; perhaps we could output to xlsx/ods and then we’d be able to benefit from proper cell merging etc too.

**Comment by CHTJonas** [comment]
Yeah I agree. The file itself is detected as UTF-8 with LF new lines in my text editors so I'm not sure why Excel is throwing it's toys out of the pram. It's maybe possible we're not following the [RFC](https://tools.ietf.org/html/rfc4180) quite as well as we should?

**Comment by CHTJonas** [comment]
So it would appear that we should actually be using CRLF for line breaks in CSV files, but I tried that and it doesn't solve the Excel issue...

**Comment by philosophicles** [comment]
FWIW the garbage is also present when opening the CSV linked above in
Google Sheets, via an Android phone.

**Comment by CHTJonas** [comment]
I managed to fix this in a somewhat hacky way using WSL:
```bash
echo -n "\xEF\xBB\xBF" > /mnt/c/Users/charlie.jonas/Downloads/bugfix.csv
cat /mnt/c/Users/charlie.jonas/Downloads/signinsheet.csv >> /mnt/c/Users/charlie.jonas/Downloads/bugfix.csv
```

Apparently there's some known Excel weirdness, and we need to include the UTF-8 byte order mark in the generated output:
- https://en.wikipedia.org/wiki/Byte_order_mark
- https://docs.microsoft.com/en-gb/windows/desktop/Intl/using-byte-order-marks
- https://stackoverflow.com/questions/155097/microsoft-excel-mangles-diacritics-in-csv-files
