### ISSUE TITLE
Alert on excessive email queue length

### ISSUE THREAD

**Issue by CHTJonas** [camdram/camdram#603]
As suggested by @philosophicles in [the chat](
https://gitter.im/camdram/webteam?at=5c71dfb11f146304210d81b1). Probably sufficient to notify if the result of the following query on the `postal` database gets out of hand:
```SQL
SELECT COUNT(*) FROM queued_messages;
```

**Comment by GKFX** [comment]
Also implement a service (probably on the SRCF) which expects to receive a unique email from Camdram every day and contacts the admins, not via webteam or any self-hosted service, if this is not received. This is largely independent of any changes to our email processes.

**Comment by CHTJonas** [comment]
I quite like infra projects so I might take this on if nobody has any objections!

I've also just realised that there's an easy way to fix this by reconfiguring Postal slightly. Currently when the queue length is exceeded and the server stop delivering new mail, Postal sends an alert message to webteam. However this message gets caught inside the server which is now not delivering. The solution is to spin up another server 'instance' within Postal and set Postal to deliver administrative alerts via this server. (Note: by "server" I mean a specific set of API keys/SMTP endpoints not an actual server process)

**Comment by GKFX** [comment]
@CHTJonas If we go with SRCF, would probably be best to set up camdram as a society on SRCF so that we can all access it rather than having it in a personal space

**Comment by CHTJonas** [comment]
Agreed - I think I recall @hoyes mentioning at one point that there was an old `camdram` society still registered on the SRCF? My thinking is a two-pronged attack:
- Separate email server instances for logically separate applications (so a barrage of spam to support won't take down the production site ability to send mail).
- Additional monitoring on SRCF to ensure things are working as expected to outside entities (other providers obviously available but at cost).

**Comment by CHTJonas** [comment]
WIP is up at [camdram/email-webtools](https://github.com/camdram/email-webtools) 🎉. Currently only reads the queue length but the aim for the next step is to have an API endpoint that return the queue length to an external service.

**Comment by CHTJonas** [comment]
I've been running the above project binary out of `/home/chtj2/email-webtools` for the past week or so and monitoring it occasionally and seems to work fine. If you make a GET request to Antigone port 8080 with the correct auth header you should see the queue length (check out the DOTENV file in that directory for credentials).

Next step is to JSONify everything and write a client that talks to the server and checks health every ~5 minutes. @GKFX how're things going with accounts on the SRCF?

**Comment by philosophicles** [comment]
One thought re SRCF - unless things have changed a lot, they presumably still require that usage is current students only. We have had times where there are no current students involved with Camdram admin. If we're going to depend on the SRCF, is that potentially a problem? 

(We should definitely also be trying really hard to always have current students involved with, and in fact leading, Camdram, but that's another problem.)

**Comment by CHTJonas** [comment]
So I believe this has changed recently and that they're happy for graduates and alumni to use SRCF services, so long as contact details are kept up-to-date. I'm not sure whether this just applies to recent students who graduate and can continue with their account, or whether alumni are allowed to apply for account retrospectively.

I agree with you on getting current students involved. There is also another issue insofar that SRCF only allows UoC members to register for accounts and it's theoretically possible that we may have someone on the team in future from Anglia Ruskin, for example.

**Comment by CHTJonas** [comment]
I am going to close this ticket. The [email-webtools](https://github.com/camdram/email-webtools) system has been deployed over the past year or so and has been very successful in alerting us to problems with the mail queue on Antigone. There's room for expansion e.g. sending and receiving a test email each day, but I think those are enhancements for the future.
