### ISSUE TITLE
Prompts to upload show/society/venue image

### ISSUE THREAD

**Issue by hoyes** [camdram/camdram#64]
Camdram doesn't have many images at the moment.

If an entity does not have an associated image and the logged in user has the necessary rights to upload one, insert a prompt where the image would be to upload an image.

**Comment by dstansby** [comment]
I've fixed this in a separate branch because #211 probably want's to be fixed before this is merged.

Currently only fixed for societies, will do shows at another point. Venues don't appear to have logos associated with them (at least looking at live camdram).
