### ISSUE TITLE
Fix regular cron errors regarding Twitter OAuth

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#682]
Regular cron errors being emailed to webteam; not on a totally consistent schedule but many per day generally. 

```
In TwitterOAuth.php line 551:

  Operation timed out after 5001 milliseconds with 0 bytes received  

camdram:entities:social-news [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```

If this is a timeout problem with the remote API endpoint, we should probably improve our timeout handling / use exponential backoff to get through it, rather than just timing out after 5 seconds.

**Comment by CHTJonas** [comment]
Related to/dupe of #512 which has a bit more in depth discussion of the issue at hand. Although I’ve notice that, compared to a few months ago, emails recently are A LOT more often. Several per day at the moment as opposed to a few per week a while back.

**Comment by philosophicles** [comment]
Whoops, yes, that's a dupe. I did search for 'twitter' and my eye clearly bounced over that one. Sorry.
