### ISSUE TITLE
Search bar makes it hard to go to the /search page

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#706]
Let's say I'm searching for a particular production of Macbeth. 

I type 'Macbeth' in the search bar. I see 10 matching results drop-down under the search bar. 

The one I want is none of these. How do I easily end up on this page: https://www.camdram.net/search?q=Macbeth - so I can see all 16 possibilities? 

Hitting enter doesn't work; it takes me to the page of the first listed result. 

Personally, I expect enter to take me to a search results page, if I don't hit the down arrow (or mouse over a result line) first. 

No idea if this has always been like this or if it's changed at some point!

**Comment by philosophicles** [comment]
Aha, this changed due to #271 - four and a half years ago. 

So the question becomes - which behaviour is better? Should we have a different way of getting to "all results" for a search query that does have matches? Or should we revert the change from #272 ? Or something else?

**Comment by CHTJonas** [comment]
There certainly used to be a link at the bottom of the search results drop-down that said something like "See more results >>" which would take you to the actual search page, but I can't seem to find the commit that removed it 😞 

In my opinion the current behaviour is _probably_ the more intuitive for the vast majority of search queries. IIRC people and shows are ranked new to old and people are then ranked additionally by number of shows from high to low - given that most of our active users will be current students I think this probably returns the correct result most of the time. But I agree we should reinstate some form of link/method of reaching the search results page.
