### ISSUE TITLE
Diary 'Jump to' quirks

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#707]
I think something is up with the Diary's 'Jump to' feature; using up to date Chrome on OS X default settings (JS not blocked, for example).

* Start on Diary page: https://www.camdram.net/diary
* Use the term picker to switch to a different term. Page updates immediately. (Working as expected; but note, no need for the 'Go' button.) 
* Use the year picker to choose a different year. Page does **not** update. 
* Hit 'Go'. Page still does not update. Definite bug at this point - I can't figure out how to see a different year in the diary. 
* Try using the term picker again. It now doesn't work: doesn't respond to clicks at all. We're stuck on whatever segment of diary we were on after using the term picker before. 

Refreshing the whole page, back to https://www.camdram.net/diary, makes the term picker work again. 

The term picker stops working as soon as _either_ the year picker _or_ Go button is interacted with; doesn't have to be both. 

So I think there are probably two defects here: 
1. Year picker should auto-refresh diary view, but does not. 
2. 'Go' button should be removed, as unnecessary if both year and term pickers trigger a refresh. 

This isn't the only possible interpretation though: maybe we don't want either picker to auto-refresh, and keep the 'Go' button, but have it not break the pickers.

**Comment by CHTJonas** [comment]
Confirmed buggy on Safari 12.1.1 / macOS 10.14.5 also.

**Comment by GKFX** [comment]
It's a mis-formed regex in `fos_js_routing` in `app/config/config.yml` that's causing problem. Fixing that causes the controls to work as designed.

I'll remove the Go button too; mobile layout now needs redoing for the smaller controls but otherwise all good.
