### ISSUE TITLE
Search index needs flushing when merging people

### ISSUE THREAD

**Issue by CHTJonas** [camdram/camdram#746]
Low priority bug. It appears that the search cache is not flushed for the affected entities when two people are merged together. This can result in stale entries in the search dropdown.

Support Ticket: [2206](https://support.camdram.net/tickets/2206)

**Comment by GKFX** [comment]
I don't think this is normal behaviour. I'm sure I usually check after doing a merge that the old search entry has gone, and also I can't reproduce this on a fresh checkout of master. Elastica is listening for the `postFlush` Doctrine event, which is called by
https://github.com/camdram/camdram/blob/cc4ed87c6b9937279bb2ea42e8ba8fd90d74207c/src/Acts/CamdramAdminBundle/Service/PeopleMerger.php#L86

On my machine looking at the Symfony profiler this all works correctly and a request to delete is sent to Elasticsearch and then carried out ok.

**Comment by CHTJonas** [comment]
@GKFX have you tested all 4 permutations of the radio buttons on the merge page? I seem to recall this was the first time a performed a merge using a URL rather than a name. Not sure why that would have any affect though...
