### ISSUE TITLE
Bug in show authorisation mechanism

### ISSUE THREAD

**Issue by CHTJonas** [camdram/camdram#747]
There seems to be a strange bug in the mechanism used to approve shows. It appears to be possible to update the `authorised` field to `0` yet still send the approval email.

@philosophicles do you remember anything unusual when you authorised this show?

Support Ticket: [2208](https://support.camdram.net/tickets/2208)

Audit Log: [Acts\CamdramBundle\Entity\Show 6992](https://www.camdram.net/admin/audit?class=Acts%5CCamdramBundle%5CEntity%5CShow&id=6992)

**Comment by GKFX** [comment]
No bug - the show was edited by admin at 2019-11-07 06:21:23, which automatically approves it and sends the email,  then de-authorised by same admin 30 seconds later using the expected method and URL `POST /shows/2019-freshers-panto-sketch-show/unapprove`. Of course this is a usability bug, that the show shouldn't automatically be approved when an admin edits it, but that should be a separate ticket.

**Comment by CHTJonas** [comment]
Oh interesting I didn't realise it automatically did that. Seems a bit strange that the audit log entry at 2019-11-07 06:21:23 shows `societies_display_list` being updated but not `authorised` but hey.

**Comment by philosophicles** [comment]
Sorry for confusion caused @CHTJonas  and @GKFX !

**Comment by GKFX** [comment]
No worries! Not your fault anyway, there's nothing you could do to make it work any better
