### ISSUE TITLE
Upgrade to Symfony 4.4

### ISSUE THREAD

**Issue by hoyes** [camdram/camdram#820]
A new Symfony LTS is out: https://symfony.com/releases/4.4

Symfony 3.4 will receive bug fixes until November (https://symfony.com/releases/3.4) so not uber-urgent but something to tackle in the medium term.

There's also Symfony Flex (https://symfony.com/doc/4.4/setup/flex.html) which mandates a new directory structure. Just upgrading Symfony should be straightforward but adopting Flex will be more invasive.

**Comment by GKFX** [comment]
Tests are now all passing again, I think the major outstanding issue now is that logging in with a new Raven account doesn't work - it produces the error
```

**Comment by hoyes** [comment]
123623764d should have fixed the login issue 😉

**Comment by GKFX** [comment]
Excellent, shall we merge the branch in then? I've added a symlink web → public so there'll be no immediate need to configure the server to look in a new location.

**Comment by CHTJonas** [comment]
Nice work! 👏
