### ISSUE TITLE
Regression in handling of punctuation when searching

### ISSUE THREAD

**Issue by CHTJonas** [camdram/camdram#886]
It's been pointed out to me that [It's True, It's True, It's True](https://www.camdram.net/shows/2020-its-true-its-true-its-true) use a RIGHT SINGLE QUOTATION MARK character instead of an APOSTROPHE character in their show title. This upset the site search if you query using an apostrophe.

I would say that this is the fault of the show for using odd punctuation in their title but I seem to recall that with Elasticsearch the query matching was punctuation-agnostic (#417)?

<img width="742" alt="Screenshot 2020-05-17 at 18 43 10" src="https://user-images.githubusercontent.com/17813061/82155683-9f9e5600-986e-11ea-87e8-b7141e8d880e.png">
<img width="723" alt="Screenshot 2020-05-17 at 18 44 39" src="https://user-images.githubusercontent.com/17813061/82155682-9f9e5600-986e-11ea-8e8c-c0ab067e1a8d.png">
<img width="749" alt="Screenshot 2020-05-17 at 18 42 59" src="https://user-images.githubusercontent.com/17813061/82155681-9ca36580-986e-11ea-9cbb-88b9aaea3211.png">

**Comment by GKFX** [comment]
Might be worth storing a normalised string in the DB for each show? MySQL's search looks difficult to configure around this otherwise. Normalisation would just mean removing the three types of apostrophe I think, as accents and double-barrelled surnames are already okay.
