### ISSUE TITLE
Should Infobase venue details be on a Venue's page?

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#97]
This is not yet a "new feature" suggestion, merely a discussion point!

Currently in v1, technical specs about venues are stored in the Infobase in a 'Venues' section.  

We have vastly-improved venue pages in v2 which could, I think, hold all that information instead.  (Not necessarily literally on the initial venue page - there could be tabs, AJAX popups, or just subpages.  I'm not suggesting a UI approach just a logical change.)

If I arrived to Camdram's homepage wanting to know the house rig of a college venue (for example) the big 'Venues' link is definitely where I'd look first.  So this seems more logical to me than storing this in the Infobase.

We also then have the option of storing it in a slightly more structured format (separate fields for "lighting", "sound" etc) because venue info tends to follow the same pattern from venue to venue.  This would encourage more consistency between venues.  

Access rights to edit - could remain open but I'd actually prefer this being under the control of the venue admins.  Other users could still suggest/request changes.  It is meant to be objective info not subjective opinions I believe.  The admins are the ones who _should_ know the correct information!

This would then make the Infobase's purpose clearer as for the information that is global to all societies, venues etc.

Thoughts? Perhaps this is a bad idea for some reason, please don't hesitate to say if it is!

**Comment by GKFX** [comment]
Closing as obsolete.
